/*
 * eap.c - Extensible Authentication Protocol for PPP (RFC 2284)
 *
 * Copyright (c) 2001 by Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Non-exclusive rights to redistribute, modify, translate, and use
 * this software in source and binary forms, in whole or in part, is
 * hereby granted, provided that the above copyright notice is
 * duplicated in any source form, and that neither the name of the
 * copyright holder nor the author is used to endorse or promote
 * products derived from this software.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 * Original version by James Carlson
 *
 * This implementation of EAP supports MD5-Challenge and SRP-SHA1
 * authentication styles.  Note that support of MD5-Challenge is a
 * requirement of RFC 2284, and that it's essentially just a
 * reimplementation of regular RFC 1994 CHAP using EAP messages.
 *
 * As an authenticator ("server"), there are multiple phases for each
 * style.  In the first phase of each style, the unauthenticated peer
 * name is queried using the EAP Identity request type.  If the
 * "remotename" option is used, then this phase is skipped, because
 * the peer's name is presumed to be known.
 *
 * For MD5-Challenge, there are two phases, and the second phase
 * consists of sending the challenge itself and handling the
 * associated response.
 *
 * For SRP-SHA1, there are four phases.  The second sends 's', 'N',
 * and 'g'.  The reply contains 'A'.  The third sends 'B', and the
 * reply contains 'M1'.  The forth sends the 'M2' value.
 *
 * As an authenticatee ("client"), there's just a single phase --
 * responding to the queries generated by the peer.  EAP is an
 * authenticator-driven protocol.
 *
 * Based on draft-ietf-pppext-eap-srp-03.txt.
 */
















pub const SHA_DIGESTSIZE: u32 = 20;



static pn_secret: &mut String = None;		/* Pseudonym generating secret */



/*
 * Command-line options.
 */
static option_t eap_option_list[] = {
    { "eap-restart", o_int, &eap_states[0].es_server.ea_timeout,
      "Set retransmit timeout for EAP Requests (server)" },
    { "eap-max-sreq", o_int, &eap_states[0].es_server.ea_maxrequests,
      "Set max number of EAP Requests sent (server)" },
    { "eap-timeout", o_int, &eap_states[0].es_client.ea_timeout,
      "Set time limit for peer EAP authentication" },
    { "eap-max-rreq", o_int, &eap_states[0].es_client.ea_maxrequests,
      "Set max number of EAP Requests allows (client)" },
    { "eap-interval", o_int, &eap_states[0].es_rechallenge,
      "Set interval for EAP rechallenge" },

    { "srp-interval", o_int, &eap_states[0].es_lwrechallenge,
      "Set interval for SRP lightweight rechallenge" },
    { "srp-pn-secret", o_string, &pn_secret,
      "Long term pseudonym generation secret" },
    { "srp-use-pseudonym", o_bool, &eap_states[0].es_usepseudo,
      "Use pseudonym if offered one by server", 1 },

    { None }
};


/*
 * Protocol entry points.
 */
pub fn eap_init(pcb: &mut ppp_pcb);
pub fn eap_input(pcb: &mut ppp_pcb, u_inp: &mut String, inlen: i32);
pub fn eap_protrej(pcb: &mut ppp_pcb);
pub fn eap_lowerup(pcb: &mut ppp_pcb);
pub fn eap_lowerdown(pcb: &mut ppp_pcb);

static int  eap_printpkt( u_inp: &mut String, inlen: i32,
    void (*)(arg: &mut Vec<u8>, fmt: &String, ...), arg: &mut Vec<u8>);


const struct protent eap_protent = {
	PPP_EAP,		/* protocol number */
	eap_init,		/* initialization procedure */
	eap_input,		/* process a received packet */
	eap_protrej,		/* process a received protocol-reject */
	eap_lowerup,		/* lower layer has gone up */
	eap_lowerdown,		/* lower layer has gone down */
	None,			/* open the protocol */
	None,			/* close the protocol */

	eap_printpkt,		/* pra: i32 packet in readable form */


	None,			/* process a received data packet */


	"EAP",			/* text name of protocol */
	None,			/* text name of corresponding data protocol */


	eap_option_list,	/* list of command-line options */
	None,			/* check requested options; assign defaults */


	None,			/* configure interface for demand-dial */
	None			/* say whether to bring up link for this pkt */

};


/*
 * A well-known 2048 bit modulus.
 */
static const u_char wkmodulus[] = {
	0xAC, 0x6B, 0xDB, 0x41, 0x32, 0x4A, 0x9A, 0x9B,
	0xF1, 0x66, 0xDE, 0x5E, 0x13, 0x89, 0x58, 0x2F,
	0xAF, 0x72, 0xB6, 0x65, 0x19, 0x87, 0xEE, 0x07,
	0xFC, 0x31, 0x92, 0x94, 0x3D, 0xB5, 0x60, 0x50,
	0xA3, 0x73, 0x29, 0xCB, 0xB4, 0xA0, 0x99, 0xED,
	0x81, 0x93, 0xE0, 0x75, 0x77, 0x67, 0xA1, 0x3D,
	0xD5, 0x23, 0x12, 0xAB, 0x4B, 0x03, 0x31, 0x0D,
	0xCD, 0x7F, 0x48, 0xA9, 0xDA, 0x04, 0xFD, 0x50,
	0xE8, 0x08, 0x39, 0x69, 0xED, 0xB7, 0x67, 0xB0,
	0xCF, 0x60, 0x95, 0x17, 0x9A, 0x16, 0x3A, 0xB3,
	0x66, 0x1A, 0x05, 0xFB, 0xD5, 0xFA, 0xAA, 0xE8,
	0x29, 0x18, 0xA9, 0x96, 0x2F, 0x0B, 0x93, 0xB8,
	0x55, 0xF9, 0x79, 0x93, 0xEC, 0x97, 0x5E, 0xEA,
	0xA8, 0x0D, 0x74, 0x0A, 0xDB, 0xF4, 0xFF, 0x74,
	0x73, 0x59, 0xD0, 0x41, 0xD5, 0xC3, 0x3E, 0xA7,
	0x1D, 0x28, 0x1E, 0x44, 0x6B, 0x14, 0x77, 0x3B,
	0xCA, 0x97, 0xB4, 0x3A, 0x23, 0xFB, 0x80, 0x16,
	0x76, 0xBD, 0x20, 0x7A, 0x43, 0x6C, 0x64, 0x81,
	0xF1, 0xD2, 0xB9, 0x07, 0x87, 0x17, 0x46, 0x1A,
	0x5B, 0x9D, 0x32, 0xE6, 0x88, 0xF8, 0x77, 0x48,
	0x54, 0x45, 0x23, 0xB5, 0x24, 0xB0, 0xD5, 0x7D,
	0x5E, 0xA7, 0x7A, 0x27, 0x75, 0xD2, 0xEC, 0xFA,
	0x03, 0x2C, 0xFB, 0xDB, 0xF5, 0x2F, 0xB3, 0x78,
	0x61, 0x60, 0x27, 0x90, 0x04, 0xE5, 0x7A, 0xE6,
	0xAF, 0x87, 0x4E, 0x73, 0x03, 0xCE, 0x53, 0x29,
	0x9C, 0xCC, 0x04, 0x1C, 0x7B, 0xC3, 0x08, 0xD8,
	0x2A, 0x56, 0x98, 0xF3, 0xA8, 0xD0, 0xC3, 0x82,
	0x71, 0xAE, 0x35, 0xF8, 0xE9, 0xDB, 0xFB, 0xB6,
	0x94, 0xB5, 0xC8, 0x03, 0xD8, 0x9F, 0x7A, 0xE4,
	0x35, 0xDE, 0x23, 0x6D, 0x52, 0x5F, 0x54, 0x75,
	0x9B, 0x65, 0xE3, 0x72, 0xFC, 0xD6, 0x8E, 0xF2,
	0x0F, 0xA7, 0x11, 0x1F, 0x9E, 0x4A, 0xFF, 0x73
};



/* Local forward declarations. */
pub fn eap_server_timeout(arg: &mut Vec<u8>);


/*
 * Convert EAP state code to printable string for debug.
 */
static const char * eap_state_name(esc: eap_state_code)
{
	static state_names: &String[] = { EAP_STATES };

	return (state_names[esc]);
}

/*
 * eap_init - Initialize state for an EAP user.  This is currently
 * called once by main() during start-up.
 */
pub fn eap_init(pcb: &mut ppp_pcb) {

	BZERO(&pcb.eap, sizeof(eap_state));

	pcb.eap.es_server.ea_id = magic();

}

/*
 * eap_client_timeout - Give up waiting for the peer to send any
 * Request messages.
 */
pub fn eap_client_timeout(arg: &mut Vec<u8>) {
	pcb: &mut ppp_pcb = arg;

	if (!eap_client_active(pcb))
		return;

	ppp_error("EAP: timeout waiting for Request from peer");
	auth_withpeer_fail(pcb, PPP_EAP);
	pcb.eap.es_client.ea_state = eapBadAuth;
}

/*
 * eap_authwithpeer - Authenticate to our peer (behave as client).
 *
 * Start client state and wait for requests.  This is called only
 * after eap_lowerup.
 */
pub fn  eap_authwithpeer(pcb: &mut ppp_pcb, localname: &String) {

	if(None == localname)
		return;

	/* Save the peer name we're given */
	pcb.eap.es_client.ea_name = localname;
	pcb.eap.es_client.ea_namelen = strlen(localname);

	pcb.eap.es_client.ea_state = eapListen;

	/*
	 * Start a timer so that if the other end just goes
	 * silent, we don't sit here waiting forever.
	 */
	if (pcb.settings.eap_req_time > 0)
		TIMEOUT(eap_client_timeout, pcb,
		    pcb.settings.eap_req_time);
}


/*
 * Format a standard EAP Failure message and send it to the peer.
 * (Server operation)
 */
pub fn eap_send_failure(pcb: &mut ppp_pcb) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;

	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + EAP_HEADERLEN), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;

	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_FAILURE, outp);
	pcb.eap.es_server.ea_id+= 1;
	PUTCHAR(pcb.eap.es_server.ea_id, outp);
	PUTSHORT(EAP_HEADERLEN, outp);

	ppp_write(pcb, p);

	pcb.eap.es_server.ea_state = eapBadAuth;
	auth_peer_fail(pcb, PPP_EAP);
}

/*
 * Format a standard EAP Success message and send it to the peer.
 * (Server operation)
 */
pub fn eap_send_success(pcb: &mut ppp_pcb) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;

	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + EAP_HEADERLEN), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;
    
	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_SUCCESS, outp);
	pcb.eap.es_server.ea_id+= 1;
	PUTCHAR(pcb.eap.es_server.ea_id, outp);
	PUTSHORT(EAP_HEADERLEN, outp);

	ppp_write(pcb, p);

	auth_peer_success(pcb, PPP_EAP, 0,
	    pcb.eap.es_server.ea_peer, pcb.eap.es_server.ea_peerlen);
}



/*
 * Set DES key according to pseudonym-generating secret and current
 * date.
 */
pub fn pncrypt_setkey(timeoffs: i32)
{
	let mut tp: &mut tm;
	let tbuf: String;
	SHA1_CTX ctxt;
	u_char dig[SHA_DIGESTSIZE];
	let reftime: time_t;

	if (pn_secret == None)
		return (0);
	reftime = time(None) + timeoffs;
	tp = localtime(&reftime);
	SHA1Init(&ctxt);
	SHA1pdate(&ctxt, pn_secret, strlen(pn_secret));
	strftime(tbuf, sizeof (tbuf), "%Y%m%d", tp);
	SHA1pdate(&ctxt, tbuf, strlen(tbuf));
	SHA1Final(dig, &ctxt);
	/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
	return (DesSetkey(dig));
}

static char base64[] =
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

struct b64state {
	let bs_bits: u32;
	let letbs_offs: i32;
};

pub fn b64enc(bs, inp, inlen, outp)
bs: &mut b64state;
u_inp: &mut String;
inlen: i32;
u_outp: &mut String;
{
	outlen: i32 = 0;

	while (inlen > 0) {
		bs.bs_bits = (bs.bs_bits << 8) | *inp+= 1;
		inlen -= 1;
		bs.bs_offs += 8;
		if (bs.bs_offs >= 24) {
			*outp+= 1 = base64[(bs.bs_bits >> 18) & 0x3F];
			*outp+= 1 = base64[(bs.bs_bits >> 12) & 0x3F];
			*outp+= 1 = base64[(bs.bs_bits >> 6) & 0x3F];
			*outp+= 1 = base64[bs.bs_bits & 0x3F];
			outlen += 4;
			bs.bs_offs = 0;
			bs.bs_bits = 0;
		}
	}
	return (outlen);
}

pub fn b64flush(bs, outp)
bs: &mut b64state;
u_outp: &mut String;
{
	outlen: i32 = 0;

	if (bs.bs_offs == 8) {
		*outp+= 1 = base64[(bs.bs_bits >> 2) & 0x3F];
		*outp+= 1 = base64[(bs.bs_bits << 4) & 0x3F];
		outlen = 2;
	} else if (bs.bs_offs == 16) {
		*outp+= 1 = base64[(bs.bs_bits >> 10) & 0x3F];
		*outp+= 1 = base64[(bs.bs_bits >> 4) & 0x3F];
		*outp+= 1 = base64[(bs.bs_bits << 2) & 0x3F];
		outlen = 3;
	}
	bs.bs_offs = 0;
	bs.bs_bits = 0;
	return (outlen);
}

pub fn b64dec(bs, inp, inlen, outp)
bs: &mut b64state;
u_inp: &mut String;
inlen: i32;
u_outp: &mut String;
{
	outlen: i32 = 0;
	let mut cp: &mut String;

	while (inlen > 0) {
		if ((cp = strchr(base64, *inp+= 1)) == None)
			break;
		bs.bs_bits = (bs.bs_bits << 6) | (cp - base64);
		inlen -= 1;
		bs.bs_offs += 6;
		if (bs.bs_offs >= 8) {
			*outp+= 1 = bs.bs_bits >> (bs.bs_offs - 8);
			outlen+= 1;
			bs.bs_offs -= 8;
		}
	}
	return (outlen);
}



/*
 * Assume that current waiting server state is complete and figure
 * next state to use based on available authentication data.  'status'
 * indicates if there was an error in handling the last query.  It is
 * 0 for success and non-zero for failure.
 */
pub fn eap_figure_next_state(pcb: &mut ppp_pcb, status: i32) {

	 char secbuf[MAXSECRETLEN], clear[8], *sp, *dp;
	let tpw: t_pw;
	tce: &mut t_confent, mytce;
	cp: &mut String, *cp2;
	let mut ts: &mut t_server;
	id: i32, i, plen, toffs;
	u_char vals[2];
	let bs: b64state;


	pcb.settings.eap_timeout_time = pcb.eap.es_savedtime;
	match (pcb.eap.es_server.ea_state) {
	eapBadAuth =>
		return;

	eapIdentify =>

		/* Discard any previous session. */
		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		if (ts != None) {
			t_serverclose(ts);
			pcb.eap.es_server.ea_session = None;
			pcb.eap.es_server.ea_skey = None;
		}

		if (status != 0) {
			pcb.eap.es_server.ea_state = eapBadAuth;
			break;
		}

		/* If we've got a pseudonym, try to decode to real name. */
		if (pcb.eap.es_server.ea_peerlen > SRP_PSEUDO_LEN &&
		    strncmp(pcb.eap.es_server.ea_peer, SRP_PSEUDO_ID,
			SRP_PSEUDO_LEN) == 0 &&
		    (pcb.eap.es_server.ea_peerlen - SRP_PSEUDO_LEN) * 3 / 4 <
		    sizeof (secbuf)) {
			BZERO(&bs, sizeof (bs));
			plen = b64dec(&bs,
			    pcb.eap.es_server.ea_peer + SRP_PSEUDO_LEN,
			    pcb.eap.es_server.ea_peerlen - SRP_PSEUDO_LEN,
			    secbuf);
			toffs = 0;
			for (i = 0; i < 5; i+= 1) {
				pncrypt_setkey(toffs);
				toffs -= 86400;
				/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
				if (!DesDecrypt(secbuf, clear)) {
					ppp_dbglog("no DES here; cannot decode "
					    "pseudonym");
					return;
				}
				id = *clear;
				if (id + 1 <= plen && id + 9 > plen)
					break;
			}
			if (plen % 8 == 0 && i < 5) {
				/*
				 * Note that this is always shorter than the
				 * original stored string, so there's no need
				 * to realloc.
				 */
				if ((i = plen = *clear) > 7)
					i = 7;
				pcb.eap.es_server.ea_peerlen = plen;
				dp = pcb.eap.es_server.ea_peer;
				MEMCPY(dp, clear + 1, i);
				plen -= i;
				dp += i;
				sp = secbuf + 8;
				while (plen > 0) {
					/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
					() DesDecrypt(sp, dp);
					sp += 8;
					dp += 8;
					plen -= 8;
				}
				pcb.eap.es_server.ea_peer[
					pcb.eap.es_server.ea_peerlen] = '\0';
				ppp_dbglog("decoded pseudonym to \"%.*q\"",
				    pcb.eap.es_server.ea_peerlen,
				    pcb.eap.es_server.ea_peer);
			} else {
				ppp_dbglog("failed to decode real name");
				/* Stay in eapIdentfy state; requery */
				break;
			}
		}
		/* Look up user in secrets database. */
		if (get_srp_secret(pcb.eap.es_unit, pcb.eap.es_server.ea_peer,
		    pcb.eap.es_server.ea_name, secbuf, 1) != 0) {
			/* Set up default in case SRP entry is bad */
			pcb.eap.es_server.ea_state = eapMD5Chall;
			/* Get t_confent based on index in srp-secrets */
			id = strtol(secbuf, &cp, 10);
			if (*cp+= 1 != ':' || id < 0)
				break;
			if (id == 0) {
				mytce.index = 0;
				mytce.modulus.data = (u_char *)wkmodulus;
				mytce.modulus.len = sizeof (wkmodulus);
				mytce.generator.data = (u_char *)"\002";
				mytce.generator.len = 1;
				tce = &mytce;
			} else if ((tce = gettcid(id)) != None) {
				/*
				 * Client will have to verify this modulus/
				 * generator combination, and that will take
				 * a while.  Lengthen the timeout here.
				 */
				if (pcb.settings.eap_timeout_time > 0 &&
				    pcb.settings.eap_timeout_time < 30)
					pcb.settings.eap_timeout_time = 30;
			} else {
				break;
			}
			if ((cp2 = strchr(cp, ':')) == None)
				break;
			*cp2+= 1 = '\0';
			tpw.pebuf.name = pcb.eap.es_server.ea_peer;
			tpw.pebuf.password.len = t_fromb64(tpw.pwbuf,
			    cp);
			tpw.pebuf.password.data = tpw.pwbuf;
			tpw.pebuf.salt.len = t_fromb64(tpw.saltbuf,
			    cp2);
			tpw.pebuf.salt.data = tpw.saltbuf;
			if ((ts = t_serveropenraw(&tpw.pebuf, tce)) == None)
				break;
			pcb.eap.es_server.ea_session = ts;
			pcb.eap.es_server.ea_state = eapSRP1;
			vals[0] = pcb.eap.es_server.ea_id + 1;
			vals[1] = EAPT_SRP;
			t_serveraddexdata(ts, vals, 2);
			/* Generate B; must call before t_servergetkey() */
			t_servergenexp(ts);
			break;
		}

		pcb.eap.es_server.ea_state = eapMD5Chall;
		break;

	eapSRP1 =>

		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		if (ts != None && status != 0) {
			t_serverclose(ts);
			pcb.eap.es_server.ea_session = None;
			pcb.eap.es_server.ea_skey = None;
		}

		if (status == 1) {
			pcb.eap.es_server.ea_state = eapMD5Chall;
		} else if (status != 0 || pcb.eap.es_server.ea_session == None) {
			pcb.eap.es_server.ea_state = eapBadAuth;
		} else {
			pcb.eap.es_server.ea_state = eapSRP2;
		}
		break;

	eapSRP2 =>

		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		if (ts != None && status != 0) {
			t_serverclose(ts);
			pcb.eap.es_server.ea_session = None;
			pcb.eap.es_server.ea_skey = None;
		}

		if (status != 0 || pcb.eap.es_server.ea_session == None) {
			pcb.eap.es_server.ea_state = eapBadAuth;
		} else {
			pcb.eap.es_server.ea_state = eapSRP3;
		}
		break;

	eapSRP3 =>
	eapSRP4 =>

		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		if (ts != None && status != 0) {
			t_serverclose(ts);
			pcb.eap.es_server.ea_session = None;
			pcb.eap.es_server.ea_skey = None;
		}

		if (status != 0 || pcb.eap.es_server.ea_session == None) {
			pcb.eap.es_server.ea_state = eapBadAuth;
		} else {
			pcb.eap.es_server.ea_state = eapOpen;
		}
		break;

	eapMD5Chall =>
		if (status != 0) {
			pcb.eap.es_server.ea_state = eapBadAuth;
		} else {
			pcb.eap.es_server.ea_state = eapOpen;
		}
		break;

	_ =>
		pcb.eap.es_server.ea_state = eapBadAuth;
		break;
	}
	if (pcb.eap.es_server.ea_state == eapBadAuth)
		eap_send_failure(pcb);
}

/*
 * Format an EAP Request message and send it to the peer.  Message
 * type depends on current state.  (Server operation)
 */
pub fn eap_send_request(pcb: &mut ppp_pcb) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let mut u_lenloc: &mut String;
	let letoutlen: i32;
	let letlen: i32;
	let str: String;

	let mut ts: &mut t_server;
	u_char clear[8], cipher[8], dig[SHA_DIGESTSIZE], *optr, *cp;
	i: i32, j;
	let b64: b64state;
	SHA1_CTX ctxt;


	/* Handle both initial auth and restart */
	if (pcb.eap.es_server.ea_state < eapIdentify &&
	    pcb.eap.es_server.ea_state != eapInitial) {
		pcb.eap.es_server.ea_state = eapIdentify;

		if (pcb.settings.explicit_remote && pcb.remote_name) {
			/*
			 * If we already know the peer's
			 * unauthenticated name, then there's no
			 * reason to ask.  Go to next state instead.
			 */
			len: i32 = strlen(pcb.remote_name);
			if (len > MAXNAMELEN) {
				len = MAXNAMELEN;
			}
			MEMCPY(pcb.eap.es_server.ea_peer, pcb.remote_name, len);
			pcb.eap.es_server.ea_peer[len] = '\0';
			pcb.eap.es_server.ea_peerlen = len;
			eap_figure_next_state(pcb, 0);
		}

	}

	if (pcb.settings.eap_max_transmits > 0 &&
	    pcb.eap.es_server.ea_requests >= pcb.settings.eap_max_transmits) {
		if (pcb.eap.es_server.ea_responses > 0)
			ppp_error("EAP: too many Requests sent");
		else
			ppp_error("EAP: no response to Requests");
		eap_send_failure(pcb);
		return;
	}

	p = pbuf_alloc(PBUF_RAW, (PPP_CTRL_PBUF_MAX_SIZE), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;
    
	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_REQUEST, outp);
	PUTCHAR(pcb.eap.es_server.ea_id, outp);
	lenloc = outp;
	INCPTR(2, outp);

	match (pcb.eap.es_server.ea_state) {
	eapIdentify =>
		PUTCHAR(EAPT_IDENTITY, outp);
		str = "Name";
		len = strlen(str);
		MEMCPY(outp, str, len);
		INCPTR(len, outp);
		break;

	eapMD5Chall =>
		PUTCHAR(EAPT_MD5CHAP, outp);
		/*
		 * pick a random challenge length between
		 * EAP_MIN_CHALLENGE_LENGTH and EAP_MAX_CHALLENGE_LENGTH
		 */
		pcb.eap.es_challen = EAP_MIN_CHALLENGE_LENGTH +
		    magic_pow(EAP_MIN_MAX_POWER_OF_TWO_CHALLENGE_LENGTH);
		PUTCHAR(pcb.eap.es_challen, outp);
		magic_random_bytes(pcb.eap.es_challenge, pcb.eap.es_challen);
		MEMCPY(outp, pcb.eap.es_challenge, pcb.eap.es_challen);
		INCPTR(pcb.eap.es_challen, outp);
		MEMCPY(outp, pcb.eap.es_server.ea_name, pcb.eap.es_server.ea_namelen);
		INCPTR(pcb.eap.es_server.ea_namelen, outp);
		break;


	eapSRP1 =>
		PUTCHAR(EAPT_SRP, outp);
		PUTCHAR(EAPSRP_CHALLENGE, outp);

		PUTCHAR(pcb.eap.es_server.ea_namelen, outp);
		MEMCPY(outp, pcb.eap.es_server.ea_name, pcb.eap.es_server.ea_namelen);
		INCPTR(pcb.eap.es_server.ea_namelen, outp);

		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		assert(ts != None);
		PUTCHAR(ts.s.len, outp);
		MEMCPY(outp, ts.s.data, ts.s.len);
		INCPTR(ts.s.len, outp);

		if (ts.g.len == 1 && ts.g.data[0] == 2) {
			PUTCHAR(0, outp);
		} else {
			PUTCHAR(ts.g.len, outp);
			MEMCPY(outp, ts.g.data, ts.g.len);
			INCPTR(ts.g.len, outp);
		}

		if (ts.n.len != sizeof (wkmodulus) ||
		    BCMP(ts.n.data, wkmodulus, sizeof (wkmodulus)) != 0) {
			MEMCPY(outp, ts.n.data, ts.n.len);
			INCPTR(ts.n.len, outp);
		}
		break;

	eapSRP2 =>
		PUTCHAR(EAPT_SRP, outp);
		PUTCHAR(EAPSRP_SKEY, outp);

		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		assert(ts != None);
		MEMCPY(outp, ts.B.data, ts.B.len);
		INCPTR(ts.B.len, outp);
		break;

	eapSRP3 =>
		PUTCHAR(EAPT_SRP, outp);
		PUTCHAR(EAPSRP_SVALIDATOR, outp);
		PUTLONG(SRPVAL_EBIT, outp);
		ts = (struct t_server *)pcb.eap.es_server.ea_session;
		assert(ts != None);
		MEMCPY(outp, t_serverresponse(ts), SHA_DIGESTSIZE);
		INCPTR(SHA_DIGESTSIZE, outp);

		if (pncrypt_setkey(0)) {
			/* Generate pseudonym */
			optr = outp;
			cp = pcb.eap.es_server.ea_peer;
			if ((j = i = pcb.eap.es_server.ea_peerlen) > 7)
				j = 7;
			clear[0] = i;
			MEMCPY(clear + 1, cp, j);
			i -= j;
			cp += j;
			/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
			if (!DesEncrypt(clear, cipher)) {
				ppp_dbglog("no DES here; not generating pseudonym");
				break;
			}
			BZERO(&b64, sizeof (b64));
			outp+= 1;		/* space for pseudonym length */
			outp += b64enc(&b64, cipher, 8, outp);
			while (i >= 8) {
				/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
				() DesEncrypt(cp, cipher);
				outp += b64enc(&b64, cipher, 8, outp);
				cp += 8;
				i -= 8;
			}
			if (i > 0) {
				MEMCPY(clear, cp, i);
				cp += i;
				magic_random_bytes(cp, 8-i);
				/* FIXME: if we want to do SRP, we need to find a way to pass the PolarSSL des_context instead of using static memory */
				() DesEncrypt(clear, cipher);
				outp += b64enc(&b64, cipher, 8, outp);
			}
			outp += b64flush(&b64, outp);

			/* Set length and pad out to next 20 octet boundary */
			i = outp - optr - 1;
			*optr = i;
			i %= SHA_DIGESTSIZE;
			if (i != 0) {
				magic_random_bytes(outp, SHA_DIGESTSIZE-i);
				INCPTR(SHA_DIGESTSIZE-i, outp);
			}

			/* Obscure the pseudonym with SHA1 hash */
			SHA1Init(&ctxt);
			SHA1pdate(&ctxt, &pcb.eap.es_server.ea_id, 1);
			SHA1pdate(&ctxt, pcb.eap.es_server.ea_skey,
			    SESSION_KEY_LEN);
			SHA1pdate(&ctxt, pcb.eap.es_server.ea_peer,
			    pcb.eap.es_server.ea_peerlen);
			while (optr < outp) {
				SHA1Final(dig, &ctxt);
				cp = dig;
				while (cp < dig + SHA_DIGESTSIZE)
					*optr+= 1 ^= *cp+= 1;
				SHA1Init(&ctxt);
				SHA1pdate(&ctxt, &pcb.eap.es_server.ea_id, 1);
				SHA1pdate(&ctxt, pcb.eap.es_server.ea_skey,
				    SESSION_KEY_LEN);
				SHA1pdate(&ctxt, optr - SHA_DIGESTSIZE,
				    SHA_DIGESTSIZE);
			}
		}
		break;

	eapSRP4 =>
		PUTCHAR(EAPT_SRP, outp);
		PUTCHAR(EAPSRP_LWRECHALLENGE, outp);
		pcb.eap.es_challen = EAP_MIN_CHALLENGE_LENGTH +
		    magic_pow(EAP_MIN_MAX_POWER_OF_TWO_CHALLENGE_LENGTH);
		magic_random_bytes(pcb.eap.es_challenge, pcb.eap.es_challen);
		MEMCPY(outp, pcb.eap.es_challenge, pcb.eap.es_challen);
		INCPTR(pcb.eap.es_challen, outp);
		break;


	_ =>
		return;
	}

	outlen = (outp - ( char*)p.payload) - PPP_HDRLEN;
	PUTSHORT(outlen, lenloc);

	pbuf_realloc(p, outlen + PPP_HDRLEN);
	ppp_write(pcb, p);

	pcb.eap.es_server.ea_requests+= 1;

	if (pcb.settings.eap_timeout_time > 0)
		TIMEOUT(eap_server_timeout, pcb, pcb.settings.eap_timeout_time);
}

/*
 * eap_authpeer - Authenticate our peer (behave as server).
 *
 * Start server state and send first request.  This is called only
 * after eap_lowerup.
 */
pub fn  eap_authpeer(pcb: &mut ppp_pcb, localname: &String) {

	/* Save the name we're given. */
	pcb.eap.es_server.ea_name = localname;
	pcb.eap.es_server.ea_namelen = strlen(localname);

	pcb.eap.es_savedtime = pcb.settings.eap_timeout_time;

	/* Lower layer up yet? */
	if (pcb.eap.es_server.ea_state == eapInitial ||
	    pcb.eap.es_server.ea_state == eapPending) {
		pcb.eap.es_server.ea_state = eapPending;
		return;
	}

	pcb.eap.es_server.ea_state = eapPending;

	/* ID number not updated here intentionally; hashed into M1 */
	eap_send_request(pcb);
}

/*
 * eap_server_timeout - Retransmission timer for sending Requests
 * expired.
 */
pub fn eap_server_timeout(arg: &mut Vec<u8>) {
	pcb: &mut ppp_pcb = arg;

	if (!eap_server_active(pcb))
		return;

	/* EAP ID number must not change on timeout. */
	eap_send_request(pcb);
}

/*
 * When it's time to send rechallenge the peer, this timeout is
 * called.  Once the rechallenge is successful, the response handler
 * will restart the timer.  If it fails, then the link is dropped.
 */
pub fn eap_rechallenge(arg: &mut Vec<u8>) {
	pcb: &mut ppp_pcb = arg;

	if (pcb.eap.es_server.ea_state != eapOpen &&
	    pcb.eap.es_server.ea_state != eapSRP4)
		return;

	pcb.eap.es_server.ea_requests = 0;
	pcb.eap.es_server.ea_state = eapIdentify;
	eap_figure_next_state(pcb, 0);
	pcb.eap.es_server.ea_id+= 1;
	eap_send_request(pcb);
}

pub fn srp_lwrechallenge(arg: &mut Vec<u8>) {
	pcb: &mut ppp_pcb = arg;

	if (pcb.eap.es_server.ea_state != eapOpen ||
	    pcb.eap.es_server.ea_type != EAPT_SRP)
		return;

	pcb.eap.es_server.ea_requests = 0;
	pcb.eap.es_server.ea_state = eapSRP4;
	pcb.eap.es_server.ea_id+= 1;
	eap_send_request(pcb);
}


/*
 * eap_lowerup - The lower layer is now up.
 *
 * This is called before either eap_authpeer or eap_authwithpeer.  See
 * link_established() in auth.c.  All that's necessary here is to
 * return to closed state so that those two routines will do the right
 * thing.
 */
pub fn eap_lowerup(pcb: &mut ppp_pcb) {
	pcb.eap.es_client.ea_state = eapClosed;

	pcb.eap.es_server.ea_state = eapClosed;

}

/*
 * eap_lowerdown - The lower layer is now down.
 *
 * Cancel all timeouts and return to initial state.
 */
pub fn eap_lowerdown(pcb: &mut ppp_pcb) {

	if (eap_client_active(pcb) && pcb.settings.eap_req_time > 0) {
		UNTIMEOUT(eap_client_timeout, pcb);
	}

	if (eap_server_active(pcb)) {
		if (pcb.settings.eap_timeout_time > 0) {
			UNTIMEOUT(eap_server_timeout, pcb);
		}
	} else {
		if ((pcb.eap.es_server.ea_state == eapOpen ||
		    pcb.eap.es_server.ea_state == eapSRP4) &&
		    pcb.eap.es_rechallenge > 0) {
			UNTIMEOUT(eap_rechallenge, pcb);
		}
		if (pcb.eap.es_server.ea_state == eapOpen &&
		    pcb.eap.es_lwrechallenge > 0) {
			UNTIMEOUT(srp_lwrechallenge, pcb);
		}
	}

	pcb.eap.es_client.ea_state = pcb.eap.es_server.ea_state = eapInitial;
	pcb.eap.es_client.ea_requests = pcb.eap.es_server.ea_requests = 0;

}

/*
 * eap_protrej - Peer doesn't speak this protocol.
 *
 * This shouldn't happen.  If it does, it represents authentication
 * failure.
 */
pub fn eap_protrej(pcb: &mut ppp_pcb) {

	if (eap_client_active(pcb)) {
		ppp_error("EAP authentication failed due to Protocol-Reject");
		auth_withpeer_fail(pcb, PPP_EAP);
	}

	if (eap_server_active(pcb)) {
		ppp_error("EAP authentication of peer failed on Protocol-Reject");
		auth_peer_fail(pcb, PPP_EAP);
	}

	eap_lowerdown(pcb);
}

/*
 * Format and send a regular EAP Response message.
 */
pub fn eap_send_response(pcb: &mut ppp_pcb, u_char id, u_char typenum,  u_str: &mut String, lenstr: i32) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let letmsglen: i32;

	msglen = EAP_HEADERLEN + sizeof (u_char) + lenstr;
	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + msglen), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;

	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_RESPONSE, outp);
	PUTCHAR(id, outp);
	pcb.eap.es_client.ea_id = id;
	PUTSHORT(msglen, outp);
	PUTCHAR(typenum, outp);
	if (lenstr > 0) {
		MEMCPY(outp, str, lenstr);
	}

	ppp_write(pcb, p);
}

/*
 * Format and send an MD5-Challenge EAP Response message.
 */
pub fn eap_chap_response(pcb: &mut ppp_pcb, u_char id, u_hash: &mut String, name: &String, namelen: i32) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let letmsglen: i32;

	msglen = EAP_HEADERLEN + 2 * sizeof (u_char) + MD5_SIGNATURE_SIZE +
	    namelen;
	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + msglen), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;
    
	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_RESPONSE, outp);
	PUTCHAR(id, outp);
	pcb.eap.es_client.ea_id = id;
	PUTSHORT(msglen, outp);
	PUTCHAR(EAPT_MD5CHAP, outp);
	PUTCHAR(MD5_SIGNATURE_SIZE, outp);
	MEMCPY(outp, hash, MD5_SIGNATURE_SIZE);
	INCPTR(MD5_SIGNATURE_SIZE, outp);
	if (namelen > 0) {
		MEMCPY(outp, name, namelen);
	}

	ppp_write(pcb, p);
}


/*
 * Format and send a SRP EAP Response message.
 */
pub fn
eap_srp_response(esp, id, subtypenum, str, lenstr)
eap_state *esp;
u_char id;
u_char subtypenum;
u_str: &mut String;
lenstr: i32;
{
	pcb: &mut ppp_pcb = &ppp_pcb_list[pcb.eap.es_unit];
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let letmsglen: i32;

	msglen = EAP_HEADERLEN + 2 * sizeof (u_char) + lenstr;
	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + msglen), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;

	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_RESPONSE, outp);
	PUTCHAR(id, outp);
	pcb.eap.es_client.ea_id = id;
	PUTSHORT(msglen, outp);
	PUTCHAR(EAPT_SRP, outp);
	PUTCHAR(subtypenum, outp);
	if (lenstr > 0) {
		MEMCPY(outp, str, lenstr);
	}

	ppp_write(pcb, p);
}

/*
 * Format and send a SRP EAP Client Validator Response message.
 */
pub fn
eap_srpval_response(esp, id, flags, str)
eap_state *esp;
u_char id;
flags: u32;
u_str: &mut String;
{
	pcb: &mut ppp_pcb = &ppp_pcb_list[pcb.eap.es_unit];
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let letmsglen: i32;

	msglen = EAP_HEADERLEN + 2 * sizeof (u_char) + sizeof  +
	    SHA_DIGESTSIZE;
	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + msglen), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;

	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_RESPONSE, outp);
	PUTCHAR(id, outp);
	pcb.eap.es_client.ea_id = id;
	PUTSHORT(msglen, outp);
	PUTCHAR(EAPT_SRP, outp);
	PUTCHAR(EAPSRP_CVALIDATOR, outp);
	PUTLONG(flags, outp);
	MEMCPY(outp, str, SHA_DIGESTSIZE);

	ppp_write(pcb, p);
}


pub fn eap_send_nak(pcb: &mut ppp_pcb, u_char id, u_char type) {
	let p: &mut pbuf;
	let mut u_outp: &mut String;
	let letmsglen: i32;

	msglen = EAP_HEADERLEN + 2 * sizeof (u_char);
	p = pbuf_alloc(PBUF_RAW, (PPP_HDRLEN + msglen), PPP_CTRL_PBUF_TYPE);
	if(None == p)
		return;
	if(p.tot_len != p.len) {
		pbuf_free(p);
		return;
	}

	outp = p.payload;

	MAKEHEADER(outp, PPP_EAP);

	PUTCHAR(EAP_RESPONSE, outp);
	PUTCHAR(id, outp);
	pcb.eap.es_client.ea_id = id;
	PUTSHORT(msglen, outp);
	PUTCHAR(EAPT_NAK, outp);
	PUTCHAR(type, outp);

	ppp_write(pcb, p);
}


static char *
name_of_pn_file()
{
	user: &mut String, *path, *file;
	let mut pw: &mut passwd;
	let pl: usize;
	static bool pnlogged = 0;

	pw = getpwuid(getuid());
	if (pw == None || (user = pw.pw_dir) == None || user[0] == 0) {
		errno = EINVAL;
		return (None);
	}
	file = _PATH_PSEUDONYM;
	pl = strlen(user) + strlen(file) + 2;
	path = malloc(pl);
	if (path == None)
		return (None);
	() slprintf(path, pl, "%s/%s", user, file);
	if (!pnlogged) {
		ppp_dbglog("pseudonym file: %s", path);
		pnlogged = 1;
	}
	return (path);
}

pub fn open_pn_file(modebits)
mode_t modebits;
{
	let mut path: &mut String;
	fd: i32, err;

	if ((path = name_of_pn_file()) == None)
		return (-1);
	fd = open(path, modebits, S_IRUSR | S_IWUSR);
	err = errno;
	free(path);
	errno = err;
	return (fd);
}

pub fn
remove_pn_file()
{
	let mut path: &mut String;

	if ((path = name_of_pn_file()) != None) {
		() unlink(path);
		() free(path);
	}
}

pub fn
write_pseudonym(esp, inp, len, id)
eap_state *esp;
u_inp: &mut String;
len: i32, id;
{
	u_char val;
	u_datp: &mut String, *digp;
	SHA1_CTX ctxt;
	u_char dig[SHA_DIGESTSIZE];
	dsize: i32, fd, olen = len;

	/*
	 * Do the decoding by working backwards.  This eliminates the need
	 * to save the decoded output in a separate buffer.
	 */
	val = id;
	while (len > 0) {
		if ((dsize = len % SHA_DIGESTSIZE) == 0)
			dsize = SHA_DIGESTSIZE;
		len -= dsize;
		datp = inp + len;
		SHA1Init(&ctxt);
		SHA1pdate(&ctxt, &val, 1);
		SHA1pdate(&ctxt, pcb.eap.es_client.ea_skey, SESSION_KEY_LEN);
		if (len > 0) {
			SHA1pdate(&ctxt, datp, SHA_DIGESTSIZE);
		} else {
			SHA1pdate(&ctxt, pcb.eap.es_client.ea_name,
			    pcb.eap.es_client.ea_namelen);
		}
		SHA1Final(dig, &ctxt);
		for (digp = dig; digp < dig + SHA_DIGESTSIZE; digp+= 1)
			*datp+= 1 ^= *digp;
	}

	/* Now check that the result is sane */
	if (olen <= 0 || *inp + 1 > olen) {
		ppp_dbglog("EAP: decoded pseudonym is unusable <%.*B>", olen, inp);
		return;
	}

	/* Save it away */
	fd = open_pn_file(O_WRONLY | O_CREAT | O_TRUNC);
	if (fd < 0) {
		ppp_dbglog("EAP: error saving pseudonym: %m");
		return;
	}
	len = write(fd, inp + 1, *inp);
	if (close(fd) != -1 && len == *inp) {
		ppp_dbglog("EAP: saved pseudonym");
		pcb.eap.es_usedpseudo = 0;
	} else {
		ppp_dbglog("EAP: failed to save pseudonym");
		remove_pn_file();
	}
}


/*
 * eap_request - Receive EAP Request message (client mode).
 */
pub fn eap_request(pcb: &mut ppp_pcb, u_inp: &mut String, id: i32, len: i32) {
	u_char typenum;
	u_char vallen;
	let letsecret_len: i32;
	let secret: String;
	let rhostname: String;
	lwip_md5_context mdContext;
	u_char hash[MD5_SIGNATURE_SIZE];

	let mut tc: &mut t_client;
	struct t_num sval, gval, Nval, *Ap, Bval;
	u_char vals[2];
	SHA1_CTX ctxt;
	u_char dig[SHA_DIGESTSIZE];
	let letfd: i32;


	/*
	 * Note: we update es_client.ea_id *only if* a Response
	 * message is being generated.  Otherwise, we leave it the
	 * same for duplicate detection purposes.
	 */

	pcb.eap.es_client.ea_requests+= 1;
	if (pcb.settings.eap_allow_req != 0 &&
	    pcb.eap.es_client.ea_requests > pcb.settings.eap_allow_req) {
		ppp_info("EAP: received too many Request messages");
		if (pcb.settings.eap_req_time > 0) {
			UNTIMEOUT(eap_client_timeout, pcb);
		}
		auth_withpeer_fail(pcb, PPP_EAP);
		return;
	}

	if (len <= 0) {
		ppp_error("EAP: empty Request message discarded");
		return;
	}

	GETCHAR(typenum, inp);
	len -= 1;

	match (typenum) {
	EAPT_IDENTITY =>
		if (len > 0)
			ppp_info("EAP: Identity prompt \"%.*q\"", len, inp);

		if (pcb.eap.es_usepseudo &&
		    (pcb.eap.es_usedpseudo == 0 ||
			(pcb.eap.es_usedpseudo == 1 &&
			    id == pcb.eap.es_client.ea_id))) {
			pcb.eap.es_usedpseudo = 1;
			/* Try to get a pseudonym */
			if ((fd = open_pn_file(O_RDONLY)) >= 0) {
				strcpy(rhostname, SRP_PSEUDO_ID);
				len = read(fd, rhostname + SRP_PSEUDO_LEN,
				    sizeof (rhostname) - SRP_PSEUDO_LEN);
				/* XXX NAI unsupported */
				if (len > 0) {
					eap_send_response(pcb, id, typenum,
					    rhostname, len + SRP_PSEUDO_LEN);
				}
				() close(fd);
				if (len > 0)
					break;
			}
		}
		/* Stop using pseudonym now. */
		if (pcb.eap.es_usepseudo && pcb.eap.es_usedpseudo != 2) {
			remove_pn_file();
			pcb.eap.es_usedpseudo = 2;
		}

		eap_send_response(pcb, id, typenum, ( u_char*)pcb.eap.es_client.ea_name,
		    pcb.eap.es_client.ea_namelen);
		break;

	EAPT_NOTIFICATION =>
		if (len > 0)
			ppp_info("EAP: Notification \"%.*q\"", len, inp);
		eap_send_response(pcb, id, typenum, None, 0);
		break;

	EAPT_NAK =>
		/*
		 * Avoid the temptation to send Response Nak in reply
		 * to Request Nak here.  It can only lead to trouble.
		 */
		ppp_warn("EAP: unexpected Nak in Request; ignored");
		/* Return because we're waiting for something real. */
		return;

	EAPT_MD5CHAP =>
		if (len < 1) {
			ppp_error("EAP: received MD5-Challenge with no data");
			/* Bogus request; wait for something real. */
			return;
		}
		GETCHAR(vallen, inp);
		len -= 1;
		if (vallen < 8 || vallen > len) {
			ppp_error("EAP: MD5-Challenge with bad length %d (8..%d)",
			    vallen, len);
			/* Try something better. */
			eap_send_nak(pcb, id, EAPT_SRP);
			break;
		}

		/* Not so likely to happen. */
		if (vallen >= len + sizeof (rhostname)) {
			ppp_dbglog("EAP: trimming really long peer name down");
			MEMCPY(rhostname, inp + vallen, sizeof (rhostname) - 1);
			rhostname[sizeof (rhostname) - 1] = '\0';
		} else {
			MEMCPY(rhostname, inp + vallen, len - vallen);
			rhostname[len - vallen] = '\0';
		}


		/* In case the remote doesn't give us his name. */
		if (pcb.settings.explicit_remote ||
		    (pcb.settings.remote_name[0] != '\0' && vallen == len))
			strlcpy(rhostname, pcb.settings.remote_name, sizeof (rhostname));


		/*
		 * Get the secret for authenticating ourselves with
		 * the specified host.
		 */
		if (!get_secret(pcb, pcb.eap.es_client.ea_name,
		    rhostname, secret, &secret_len, 0)) {
			ppp_dbglog("EAP: no MD5 secret for auth to %q", rhostname);
			eap_send_nak(pcb, id, EAPT_SRP);
			break;
		}
		lwip_md5_init(&mdContext);
		lwip_md5_starts(&mdContext);
		typenum = id;
		lwip_md5_update(&mdContext, &typenum, 1);
		lwip_md5_update(&mdContext, (u_char *)secret, secret_len);
		BZERO(secret, sizeof (secret));
		lwip_md5_update(&mdContext, inp, vallen);
		lwip_md5_finish(&mdContext, hash);
		lwip_md5_free(&mdContext);
		eap_chap_response(pcb, id, hash, pcb.eap.es_client.ea_name,
		    pcb.eap.es_client.ea_namelen);
		break;


	EAPT_SRP =>
		if (len < 1) {
			ppp_error("EAP: received empty SRP Request");
			/* Bogus request; wait for something real. */
			return;
		}

		/* Get subtype */
		GETCHAR(vallen, inp);
		len -= 1;
		match (vallen) {
		EAPSRP_CHALLENGE =>
			tc = None;
			if (pcb.eap.es_client.ea_session != None) {
				tc = (struct t_client *)pcb.eap.es_client.
				    ea_session;
				/*
				 * If this is a new challenge, then start
				 * over with a new client session context.
				 * Otherwise, just resend last response.
				 */
				if (id != pcb.eap.es_client.ea_id) {
					t_clientclose(tc);
					pcb.eap.es_client.ea_session = None;
					tc = None;
				}
			}
			/* No session key just yet */
			pcb.eap.es_client.ea_skey = None;
			if (tc == None) {
				let letrhostnamelen: i32;

				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen >= len) {
					ppp_error("EAP: badly-formed SRP Challenge"
					    " (name)");
					/* Ignore badly-formed messages */
					return;
				}
				MEMCPY(rhostname, inp, vallen);
				rhostname[vallen] = '\0';
				INCPTR(vallen, inp);
				len -= vallen;

				/*
				 * In case the remote doesn't give us his name,
				 * use configured name.
				 */
				if (explicit_remote ||
				    (remote_name[0] != '\0' && vallen == 0)) {
					strlcpy(rhostname, remote_name,
					    sizeof (rhostname));
				}

				rhostnamelen = strlen(rhostname);
				if (rhostnamelen > MAXNAMELEN) {
					rhostnamelen = MAXNAMELEN;
				}
				MEMCPY(pcb.eap.es_client.ea_peer, rhostname, rhostnamelen);
				pcb.eap.es_client.ea_peer[rhostnamelen] = '\0';
				pcb.eap.es_client.ea_peerlen = rhostnamelen;

				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen >= len) {
					ppp_error("EAP: badly-formed SRP Challenge"
					    " (s)");
					/* Ignore badly-formed messages */
					return;
				}
				sval.data = inp;
				sval.len = vallen;
				INCPTR(vallen, inp);
				len -= vallen;

				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen > len) {
					ppp_error("EAP: badly-formed SRP Challenge"
					    " (g)");
					/* Ignore badly-formed messages */
					return;
				}
				/* If no generator present, then use value 2 */
				if (vallen == 0) {
					gval.data = (u_char *)"\002";
					gval.len = 1;
				} else {
					gval.data = inp;
					gval.len = vallen;
				}
				INCPTR(vallen, inp);
				len -= vallen;

				/*
				 * If no modulus present, then use well-known
				 * value.
				 */
				if (len == 0) {
					Nval.data = (u_char *)wkmodulus;
					Nval.len = sizeof (wkmodulus);
				} else {
					Nval.data = inp;
					Nval.len = len;
				}
				tc = t_clientopen(pcb.eap.es_client.ea_name,
				    &Nval, &gval, &sval);
				if (tc == None) {
					eap_send_nak(pcb, id, EAPT_MD5CHAP);
					break;
				}
				pcb.eap.es_client.ea_session = tc;

				/* Add Challenge ID & type to verifier */
				vals[0] = id;
				vals[1] = EAPT_SRP;
				t_clientaddexdata(tc, vals, 2);
			}
			Ap = t_clientgenexp(tc);
			eap_srp_response(esp, id, EAPSRP_CKEY, Ap.data,
			    Ap.len);
			break;

		EAPSRP_SKEY =>
			tc = (struct t_client *)pcb.eap.es_client.ea_session;
			if (tc == None) {
				ppp_warn("EAP: peer sent Subtype 2 without 1");
				eap_send_nak(pcb, id, EAPT_MD5CHAP);
				break;
			}
			if (pcb.eap.es_client.ea_skey != None) {
				/*
				 * ID number should not change here.  Warn
				 * if it does (but otherwise ignore).
				 */
				if (id != pcb.eap.es_client.ea_id) {
					ppp_warn("EAP: ID changed from %d to %d "
					    "in SRP Subtype 2 rexmit",
					    pcb.eap.es_client.ea_id, id);
				}
			} else {
				if (get_srp_secret(pcb.eap.es_unit,
				    pcb.eap.es_client.ea_name,
				    pcb.eap.es_client.ea_peer, secret, 0) == 0) {
					/*
					 * Can't work with this peer because
					 * the secret is missing.  Just give
					 * up.
					 */
					eap_send_nak(pcb, id, EAPT_MD5CHAP);
					break;
				}
				Bval.data = inp;
				Bval.len = len;
				t_clientpasswd(tc, secret);
				BZERO(secret, sizeof (secret));
				pcb.eap.es_client.ea_skey =
				    t_clientgetkey(tc, &Bval);
				if (pcb.eap.es_client.ea_skey == None) {
					/* Server is rogue; stop now */
					ppp_error("EAP: SRP server is rogue");
					// goto client_failure;
				}
			}
			eap_srpval_response(esp, id, SRPVAL_EBIT,
			    t_clientresponse(tc));
			break;

		EAPSRP_SVALIDATOR =>
			tc = (struct t_client *)pcb.eap.es_client.ea_session;
			if (tc == None || pcb.eap.es_client.ea_skey == None) {
				ppp_warn("EAP: peer sent Subtype 3 without 1/2");
				eap_send_nak(pcb, id, EAPT_MD5CHAP);
				break;
			}
			/*
			 * If we're already open, then this ought to be a
			 * duplicate.  Otherwise, check that the server is
			 * who we think it is.
			 */
			if (pcb.eap.es_client.ea_state == eapOpen) {
				if (id != pcb.eap.es_client.ea_id) {
					ppp_warn("EAP: ID changed from %d to %d "
					    "in SRP Subtype 3 rexmit",
					    pcb.eap.es_client.ea_id, id);
				}
			} else {
				len -= sizeof  + SHA_DIGESTSIZE;
				if (len < 0 || t_clientverify(tc, inp +
					sizeof ) != 0) {
					ppp_error("EAP: SRP server verification "
					    "failed");
					// goto client_failure;
				}
				GETLONG(pcb.eap.es_client.ea_keyflags, inp);
				/* Save pseudonym if user wants it. */
				if (len > 0 && pcb.eap.es_usepseudo) {
					INCPTR(SHA_DIGESTSIZE, inp);
					write_pseudonym(esp, inp, len, id);
				}
			}
			/*
			 * We've verified our peer.  We're now mostly done,
			 * except for waiting on the regular EAP Success
			 * message.
			 */
			eap_srp_response(esp, id, EAPSRP_ACK, None, 0);
			break;

		EAPSRP_LWRECHALLENGE =>
			if (len < 4) {
				ppp_warn("EAP: malformed Lightweight rechallenge");
				return;
			}
			SHA1Init(&ctxt);
			vals[0] = id;
			SHA1pdate(&ctxt, vals, 1);
			SHA1pdate(&ctxt, pcb.eap.es_client.ea_skey,
			    SESSION_KEY_LEN);
			SHA1pdate(&ctxt, inp, len);
			SHA1pdate(&ctxt, pcb.eap.es_client.ea_name,
			    pcb.eap.es_client.ea_namelen);
			SHA1Final(dig, &ctxt);
			eap_srp_response(esp, id, EAPSRP_LWRECHALLENGE, dig,
			    SHA_DIGESTSIZE);
			break;

		_ =>
			ppp_error("EAP: unknown SRP Subtype %d", vallen);
			eap_send_nak(pcb, id, EAPT_MD5CHAP);
			break;
		}
		break;


	_ =>
		ppp_info("EAP: unknown authentication type %d; Naking", typenum);
		eap_send_nak(pcb, id, EAPT_SRP);
		break;
	}

	if (pcb.settings.eap_req_time > 0) {
		UNTIMEOUT(eap_client_timeout, pcb);
		TIMEOUT(eap_client_timeout, pcb,
		    pcb.settings.eap_req_time);
	}
	return;


// client_failure:
	pcb.eap.es_client.ea_state = eapBadAuth;
	if (pcb.settings.eap_req_time > 0) {
		UNTIMEOUT(eap_client_timeout, esp);
	}
	pcb.eap.es_client.ea_session = None;
	t_clientclose(tc);
	auth_withpeer_fail(pcb, PPP_EAP);

}


/*
 * eap_response - Receive EAP Response message (server mode).
 */
pub fn eap_response(pcb: &mut ppp_pcb, u_inp: &mut String, id: i32, len: i32) {
	u_char typenum;
	u_char vallen;
	let letsecret_len: i32;
	let secret: String;
	let rhostname: String;
	lwip_md5_context mdContext;
	u_char hash[MD5_SIGNATURE_SIZE];

	let mut ts: &mut t_server;
	let A: t_num;
	SHA1_CTX ctxt;
	u_char dig[SHA_DIGESTSIZE];


	if (pcb.eap.es_server.ea_id != id) {
		ppp_dbglog("EAP: discarding Response %d; expected ID %d", id,
		    pcb.eap.es_server.ea_id);
		return;
	}

	pcb.eap.es_server.ea_responses+= 1;

	if (len <= 0) {
		ppp_error("EAP: empty Response message discarded");
		return;
	}

	GETCHAR(typenum, inp);
	len -= 1;

	match (typenum) {
	EAPT_IDENTITY =>
		if (pcb.eap.es_server.ea_state != eapIdentify) {
			ppp_dbglog("EAP discarding unwanted Identify \"%.q\"", len,
			    inp);
			break;
		}
		ppp_info("EAP: unauthenticated peer name \"%.*q\"", len, inp);
		if (len > MAXNAMELEN) {
		  len = MAXNAMELEN;
		}
		MEMCPY(pcb.eap.es_server.ea_peer, inp, len);
		pcb.eap.es_server.ea_peer[len] = '\0';
		pcb.eap.es_server.ea_peerlen = len;
		eap_figure_next_state(pcb, 0);
		break;

	EAPT_NOTIFICATION =>
		ppp_dbglog("EAP unexpected Notification; response discarded");
		break;

	EAPT_NAK =>
		if (len < 1) {
			ppp_info("EAP: Nak Response with no suggested protocol");
			eap_figure_next_state(pcb, 1);
			break;
		}

		GETCHAR(vallen, inp);
		len -= 1;

		if (

		!pcb.explicit_remote &&

		pcb.eap.es_server.ea_state == eapIdentify){
			/* Peer cannot Nak Identify Request */
			eap_figure_next_state(pcb, 1);
			break;
		}

		match (vallen) {
		EAPT_SRP =>
			/* Run through SRP validator selection again. */
			pcb.eap.es_server.ea_state = eapIdentify;
			eap_figure_next_state(pcb, 0);
			break;

		EAPT_MD5CHAP =>
			pcb.eap.es_server.ea_state = eapMD5Chall;
			break;

		_ =>
			ppp_dbglog("EAP: peer requesting unknown Type %d", vallen);
			match (pcb.eap.es_server.ea_state) {
			eapSRP1 =>
			eapSRP2 =>
			eapSRP3 =>
				pcb.eap.es_server.ea_state = eapMD5Chall;
				break;
			eapMD5Chall =>
			eapSRP4 =>
				pcb.eap.es_server.ea_state = eapIdentify;
				eap_figure_next_state(pcb, 0);
				break;
			_ =>
				break;
			}
			break;
		}
		break;

	EAPT_MD5CHAP =>
		if (pcb.eap.es_server.ea_state != eapMD5Chall) {
			ppp_error("EAP: unexpected MD5-Response");
			eap_figure_next_state(pcb, 1);
			break;
		}
		if (len < 1) {
			ppp_error("EAP: received MD5-Response with no data");
			eap_figure_next_state(pcb, 1);
			break;
		}
		GETCHAR(vallen, inp);
		len -= 1;
		if (vallen != 16 || vallen > len) {
			ppp_error("EAP: MD5-Response with bad length %d", vallen);
			eap_figure_next_state(pcb, 1);
			break;
		}

		/* Not so likely to happen. */
		if (vallen >= len + sizeof (rhostname)) {
			ppp_dbglog("EAP: trimming really long peer name down");
			MEMCPY(rhostname, inp + vallen, sizeof (rhostname) - 1);
			rhostname[sizeof (rhostname) - 1] = '\0';
		} else {
			MEMCPY(rhostname, inp + vallen, len - vallen);
			rhostname[len - vallen] = '\0';
		}


		/* In case the remote doesn't give us his name. */
		if (explicit_remote ||
		    (remote_name[0] != '\0' && vallen == len))
			strlcpy(rhostname, remote_name, sizeof (rhostname));


		/*
		 * Get the secret for authenticating the specified
		 * host.
		 */
		if (!get_secret(pcb, rhostname,
		    pcb.eap.es_server.ea_name, secret, &secret_len, 1)) {
			ppp_dbglog("EAP: no MD5 secret for auth of %q", rhostname);
			eap_send_failure(pcb);
			break;
		}
		lwip_md5_init(&mdContext);
		lwip_md5_starts(&mdContext);
		lwip_md5_update(&mdContext, &pcb.eap.es_server.ea_id, 1);
		lwip_md5_update(&mdContext, (u_char *)secret, secret_len);
		BZERO(secret, sizeof (secret));
		lwip_md5_update(&mdContext, pcb.eap.es_challenge, pcb.eap.es_challen);
		lwip_md5_finish(&mdContext, hash);
		lwip_md5_free(&mdContext);
		if (BCMP(hash, inp, MD5_SIGNATURE_SIZE) != 0) {
			eap_send_failure(pcb);
			break;
		}
		pcb.eap.es_server.ea_type = EAPT_MD5CHAP;
		eap_send_success(pcb);
		eap_figure_next_state(pcb, 0);
		if (pcb.eap.es_rechallenge != 0)
			TIMEOUT(eap_rechallenge, pcb, pcb.eap.es_rechallenge);
		break;


	EAPT_SRP =>
		if (len < 1) {
			ppp_error("EAP: empty SRP Response");
			eap_figure_next_state(pcb, 1);
			break;
		}
		GETCHAR(typenum, inp);
		len -= 1;
		match (typenum) {
		EAPSRP_CKEY =>
			if (pcb.eap.es_server.ea_state != eapSRP1) {
				ppp_error("EAP: unexpected SRP Subtype 1 Response");
				eap_figure_next_state(pcb, 1);
				break;
			}
			A.data = inp;
			A.len = len;
			ts = (struct t_server *)pcb.eap.es_server.ea_session;
			assert(ts != None);
			pcb.eap.es_server.ea_skey = t_servergetkey(ts, &A);
			if (pcb.eap.es_server.ea_skey == None) {
				/* Client's A value is bogus; terminate now */
				ppp_error("EAP: bogus A value from client");
				eap_send_failure(pcb);
			} else {
				eap_figure_next_state(pcb, 0);
			}
			break;

		EAPSRP_CVALIDATOR =>
			if (pcb.eap.es_server.ea_state != eapSRP2) {
				ppp_error("EAP: unexpected SRP Subtype 2 Response");
				eap_figure_next_state(pcb, 1);
				break;
			}
			if (len < sizeof  + SHA_DIGESTSIZE) {
				ppp_error("EAP: M1 length %d < %d", len,
				    sizeof  + SHA_DIGESTSIZE);
				eap_figure_next_state(pcb, 1);
				break;
			}
			GETLONG(pcb.eap.es_server.ea_keyflags, inp);
			ts = (struct t_server *)pcb.eap.es_server.ea_session;
			assert(ts != None);
			if (t_serververify(ts, inp)) {
				ppp_info("EAP: unable to validate client identity");
				eap_send_failure(pcb);
				break;
			}
			eap_figure_next_state(pcb, 0);
			break;

		EAPSRP_ACK =>
			if (pcb.eap.es_server.ea_state != eapSRP3) {
				ppp_error("EAP: unexpected SRP Subtype 3 Response");
				eap_send_failure(esp);
				break;
			}
			pcb.eap.es_server.ea_type = EAPT_SRP;
			eap_send_success(pcb, esp);
			eap_figure_next_state(pcb, 0);
			if (pcb.eap.es_rechallenge != 0)
				TIMEOUT(eap_rechallenge, pcb,
				    pcb.eap.es_rechallenge);
			if (pcb.eap.es_lwrechallenge != 0)
				TIMEOUT(srp_lwrechallenge, pcb,
				    pcb.eap.es_lwrechallenge);
			break;

		EAPSRP_LWRECHALLENGE =>
			if (pcb.eap.es_server.ea_state != eapSRP4) {
				ppp_info("EAP: unexpected SRP Subtype 4 Response");
				return;
			}
			if (len != SHA_DIGESTSIZE) {
				ppp_error("EAP: bad Lightweight rechallenge "
				    "response");
				return;
			}
			SHA1Init(&ctxt);
			vallen = id;
			SHA1pdate(&ctxt, &vallen, 1);
			SHA1pdate(&ctxt, pcb.eap.es_server.ea_skey,
			    SESSION_KEY_LEN);
			SHA1pdate(&ctxt, pcb.eap.es_challenge, pcb.eap.es_challen);
			SHA1pdate(&ctxt, pcb.eap.es_server.ea_peer,
			    pcb.eap.es_server.ea_peerlen);
			SHA1Final(dig, &ctxt);
			if (BCMP(dig, inp, SHA_DIGESTSIZE) != 0) {
				ppp_error("EAP: failed Lightweight rechallenge");
				eap_send_failure(pcb);
				break;
			}
			pcb.eap.es_server.ea_state = eapOpen;
			if (pcb.eap.es_lwrechallenge != 0)
				TIMEOUT(srp_lwrechallenge, esp,
				    pcb.eap.es_lwrechallenge);
			break;
		}
		break;


	_ =>
		/* This can't happen. */
		ppp_error("EAP: unknown Response type %d; ignored", typenum);
		return;
	}

	if (pcb.settings.eap_timeout_time > 0) {
		UNTIMEOUT(eap_server_timeout, pcb);
	}

	if (pcb.eap.es_server.ea_state != eapBadAuth &&
	    pcb.eap.es_server.ea_state != eapOpen) {
		pcb.eap.es_server.ea_id+= 1;
		eap_send_request(pcb);
	}
}


/*
 * eap_success - Receive EAP Success message (client mode).
 */
pub fn eap_success(pcb: &mut ppp_pcb, u_inp: &mut String, id: i32, len: i32) {
	

	if (pcb.eap.es_client.ea_state != eapOpen && !eap_client_active(pcb)) {
		ppp_dbglog("EAP unexpected success message in state %s (%d)",
		    eap_state_name(pcb.eap.es_client.ea_state),
		    pcb.eap.es_client.ea_state);
		return;
	}

	if (pcb.settings.eap_req_time > 0) {
		UNTIMEOUT(eap_client_timeout, pcb);
	}

	if (len > 0) {
		/* This is odd.  The spec doesn't allow for this. */
		PRINTMSG(inp, len);
	}

	pcb.eap.es_client.ea_state = eapOpen;
	auth_withpeer_success(pcb, PPP_EAP, 0);
}

/*
 * eap_failure - Receive EAP Failure message (client mode).
 */
pub fn eap_failure(pcb: &mut ppp_pcb, u_inp: &mut String, id: i32, len: i32) {
	

	if (!eap_client_active(pcb)) {
		ppp_dbglog("EAP unexpected failure message in state %s (%d)",
		    eap_state_name(pcb.eap.es_client.ea_state),
		    pcb.eap.es_client.ea_state);
	}

	if (pcb.settings.eap_req_time > 0) {
		UNTIMEOUT(eap_client_timeout, pcb);
	}

	if (len > 0) {
		/* This is odd.  The spec doesn't allow for this. */
		PRINTMSG(inp, len);
	}

	pcb.eap.es_client.ea_state = eapBadAuth;

	ppp_error("EAP: peer reports authentication failure");
	auth_withpeer_fail(pcb, PPP_EAP);
}

/*
 * eap_input - Handle received EAP message.
 */
pub fn eap_input(pcb: &mut ppp_pcb, u_inp: &mut String, inlen: i32) {
	u_char code, id;
	let letlen: i32;

	/*
	 * Parse header (code, id and length).  If packet too short,
	 * drop it.
	 */
	if (inlen < EAP_HEADERLEN) {
		ppp_error("EAP: packet too short: %d < %d", inlen, EAP_HEADERLEN);
		return;
	}
	GETCHAR(code, inp);
	GETCHAR(id, inp);
	GETSHORT(len, inp);
	if (len < EAP_HEADERLEN || len > inlen) {
		ppp_error("EAP: packet has illegal length field %d (%d..%d)", len,
		    EAP_HEADERLEN, inlen);
		return;
	}
	len -= EAP_HEADERLEN;

	/* Dispatch based on message code */
	match (code) {
	EAP_REQUEST =>
		eap_request(pcb, inp, id, len);
		break;


	EAP_RESPONSE =>
		eap_response(pcb, inp, id, len);
		break;


	EAP_SUCCESS =>
		eap_success(pcb, inp, id, len);
		break;

	EAP_FAILURE =>
		eap_failure(pcb, inp, id, len);
		break;

	_ =>				/* XXX Need code reject */
		/* Note: it's not legal to send EAP Nak here. */
		ppp_warn("EAP: unknown code %d received", code);
		break;
	}
}


/*
 * eap_printpkt - prthe: i32 contents of an EAP packet.
 */
static const char* const eap_codenames[] = {
	"Request", "Response", "Success", "Failure"
};

static const char* const eap_typenames[] = {
	"Identity", "Notification", "Nak", "MD5-Challenge",
	"OTP", "Generic-Token", None, None,
	"RSA", "DSS", "KEA", "KEA-Validate",
	"TLS", "Defender", "Windows 2000", "Arcot",
	"Cisco", "Nokia", "SRP"
};

static eap_printpkt: i32( u_inp: &mut String, inlen: i32, void (*printer) (void *,  char *, ...), arg: &mut Vec<u8>) {
	code: i32, id, len, rtype, vallen;
 let mut u_pstart: &mut String;
	let uval: u32;

	if (inlen < EAP_HEADERLEN)
		return (0);
	pstart = inp;
	GETCHAR(code, inp);
	GETCHAR(id, inp);
	GETSHORT(len, inp);
	if (len < EAP_HEADERLEN || len > inlen)
		return (0);

	if (code >= 1 && code <= LWIP_ARRAYSIZE(eap_codenames))
		printer(arg, " %s", eap_codenames[code-1]);
	else
		printer(arg, " code=0x%x", code);
	printer(arg, " id=0x%x", id);
	len -= EAP_HEADERLEN;
	match (code) {
	EAP_REQUEST =>
		if (len < 1) {
			printer(arg, " <missing type>");
			break;
		}
		GETCHAR(rtype, inp);
		len -= 1;
		if (rtype >= 1 && rtype <= LWIP_ARRAYSIZE(eap_typenames))
			printer(arg, " %s", eap_typenames[rtype-1]);
		else
			printer(arg, " type=0x%x", rtype);
		match (rtype) {
		EAPT_IDENTITY =>
		EAPT_NOTIFICATION =>
			if (len > 0) {
				printer(arg, " <Message ");
				ppp_print_string(inp, len, printer, arg);
				printer(arg, ">");
				INCPTR(len, inp);
				len = 0;
			} else {
				printer(arg, " <No message>");
			}
			break;

		EAPT_MD5CHAP =>
			if (len <= 0)
				break;
			GETCHAR(vallen, inp);
			len -= 1;
			if (vallen > len)
				// goto truncated;
			printer(arg, " <Value%.*B>", vallen, inp);
			INCPTR(vallen, inp);
			len -= vallen;
			if (len > 0) {
				printer(arg, " <Name ");
				ppp_print_string(inp, len, printer, arg);
				printer(arg, ">");
				INCPTR(len, inp);
				len = 0;
			} else {
				printer(arg, " <No name>");
			}
			break;

		EAPT_SRP =>
			if (len < 3)
				// goto truncated;
			GETCHAR(vallen, inp);
			len -= 1;
			printer(arg, "-%d", vallen);
			match (vallen) {
			EAPSRP_CHALLENGE =>
				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen >= len)
					// goto truncated;
				if (vallen > 0) {
					printer(arg, " <Name ");
					ppp_print_string(inp, vallen, printer,
					    arg);
					printer(arg, ">");
				} else {
					printer(arg, " <No name>");
				}
				INCPTR(vallen, inp);
				len -= vallen;
				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen >= len)
					// goto truncated;
				printer(arg, " <s%.*B>", vallen, inp);
				INCPTR(vallen, inp);
				len -= vallen;
				GETCHAR(vallen, inp);
				len -= 1;
				if (vallen > len)
					// goto truncated;
				if (vallen == 0) {
					printer(arg, " <Default g=2>");
				} else {
					printer(arg, " <g%.*B>", vallen, inp);
				}
				INCPTR(vallen, inp);
				len -= vallen;
				if (len == 0) {
					printer(arg, " <Default N>");
				} else {
					printer(arg, " <N%.*B>", len, inp);
					INCPTR(len, inp);
					len = 0;
				}
				break;

			EAPSRP_SKEY =>
				printer(arg, " <B%.*B>", len, inp);
				INCPTR(len, inp);
				len = 0;
				break;

			EAPSRP_SVALIDATOR =>
				if (len < sizeof )
					break;
				GETLONG(uval, inp);
				len -= sizeof ;
				if (uval & SRPVAL_EBIT) {
					printer(arg, " E");
					uval &= !SRPVAL_EBIT;
				}
				if (uval != 0) {
					printer(arg, " f<%X>", uval);
				}
				if ((vallen = len) > SHA_DIGESTSIZE)
					vallen = SHA_DIGESTSIZE;
				printer(arg, " <M2%.*B%s>", len, inp,
				    len < SHA_DIGESTSIZE ? "?" : "");
				INCPTR(vallen, inp);
				len -= vallen;
				if (len > 0) {
					printer(arg, " <PN%.*B>", len, inp);
					INCPTR(len, inp);
					len = 0;
				}
				break;

			EAPSRP_LWRECHALLENGE =>
				printer(arg, " <Challenge%.*B>", len, inp);
				INCPTR(len, inp);
				len = 0;
				break;
			_ =>
				break;
			}
			break;
		_ =>
			break;
		}
		break;

	EAP_RESPONSE =>
		if (len < 1)
			break;
		GETCHAR(rtype, inp);
		len -= 1;
		if (rtype >= 1 && rtype <= LWIP_ARRAYSIZE(eap_typenames))
			printer(arg, " %s", eap_typenames[rtype-1]);
		else
			printer(arg, " type=0x%x", rtype);
		match (rtype) {
		EAPT_IDENTITY =>
			if (len > 0) {
				printer(arg, " <Name ");
				ppp_print_string(inp, len, printer, arg);
				printer(arg, ">");
				INCPTR(len, inp);
				len = 0;
			}
			break;

		EAPT_NAK =>
			if (len <= 0) {
				printer(arg, " <missing hint>");
				break;
			}
			GETCHAR(rtype, inp);
			len -= 1;
			printer(arg, " <Suggested-type %02X", rtype);
			if (rtype >= 1 && rtype < LWIP_ARRAYSIZE(eap_typenames))
				printer(arg, " (%s)", eap_typenames[rtype-1]);
			printer(arg, ">");
			break;

		EAPT_MD5CHAP =>
			if (len <= 0) {
				printer(arg, " <missing length>");
				break;
			}
			GETCHAR(vallen, inp);
			len -= 1;
			if (vallen > len)
				// goto truncated;
			printer(arg, " <Value%.*B>", vallen, inp);
			INCPTR(vallen, inp);
			len -= vallen;
			if (len > 0) {
				printer(arg, " <Name ");
				ppp_print_string(inp, len, printer, arg);
				printer(arg, ">");
				INCPTR(len, inp);
				len = 0;
			} else {
				printer(arg, " <No name>");
			}
			break;

		EAPT_SRP =>
			if (len < 1)
				// goto truncated;
			GETCHAR(vallen, inp);
			len -= 1;
			printer(arg, "-%d", vallen);
			match (vallen) {
			EAPSRP_CKEY =>
				printer(arg, " <A%.*B>", len, inp);
				INCPTR(len, inp);
				len = 0;
				break;

			EAPSRP_CVALIDATOR =>
				if (len < sizeof )
					break;
				GETLONG(uval, inp);
				len -= sizeof ;
				if (uval & SRPVAL_EBIT) {
					printer(arg, " E");
					uval &= !SRPVAL_EBIT;
				}
				if (uval != 0) {
					printer(arg, " f<%X>", uval);
				}
				printer(arg, " <M1%.*B%s>", len, inp,
				    len == SHA_DIGESTSIZE ? "" : "?");
				INCPTR(len, inp);
				len = 0;
				break;

			EAPSRP_ACK =>
				break;

			EAPSRP_LWRECHALLENGE =>
				printer(arg, " <Response%.*B%s>", len, inp,
				    len == SHA_DIGESTSIZE ? "" : "?");
				if ((vallen = len) > SHA_DIGESTSIZE)
					vallen = SHA_DIGESTSIZE;
				INCPTR(vallen, inp);
				len -= vallen;
				break;
			_ =>
				break;
			}
			break;
		_ =>
			break;
		}
		break;

	EAP_SUCCESS =>	/* No payload expected for these! */
	EAP_FAILURE =>
	_ =>
		break;

	// truncated:
		printer(arg, " <truncated>");
		break;
	}

	if (len > 8)
		printer(arg, "%8B...", inp);
	else if (len > 0)
		printer(arg, "%.*B", len, inp);
	INCPTR(len, inp);

	return (inp - pstart);
}



