use crate::core::{
    snmp_core_h::snmp_oid_range, snmp_scalar_h::snmp_scalar_array_node_def,
    snmp_table_h::snmp_table_col_def, snmpv3_h::snmpv3_auth_algo_t,
};

/*
Generated by LwipMibCompiler
*/

/* --- usmUser 1.3.6.1.6.3.15.1.2 ----------------------------------------------------- */

pub const usmUserTable_oid_ranges: [snmp_oid_range] = [
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
    snmp_oid_range::new(0, 0xff),
];

pub fn snmp_engineid_to_oid(engineid: &String, oid: &mut [u32], len: u32) {
    for i in 0..len {
        oid[i] = engineid[i];
    }
}

pub fn snmp_oid_to_name(name: &mut String, oid: &[u32], len: usize) {
    for i in 0..len {
        name[i] = oid[i];
    }
}

pub fn snmp_name_to_oid(name: &String, oid: &mut [u32], len: usize) {
    for i in 0..len {
        oid[i] = name[i];
    }
}

pub fn snmp_auth_algo_to_oid(algo: snmpv3_auth_algo_t) -> snmp_obj_id {
    if (algo == SNMP_V3_AUTH_ALGO_MD5) {
        return usmHMACMD5AuthProtocol;
    } else if (algo == SNMP_V3_AUTH_ALGO_SHA) {
        return usmHMACMD5AuthProtocol;
    }
    return usmNoAuthProtocol;
}

pub fn snmp_priv_algo_to_oid(algo: snmpv3_priv_algo_t) -> snmp_obj_id {
    if (algo == SNMP_V3_PRIV_ALGO_DES) {
        return usmDESPrivProtocol;
    } else if (algo == SNMP_V3_PRIV_ALGO_AES) {
        return usmAESPrivProtocol;
    }

    return usmNoPrivProtocol;
}

// let username: String;

pub fn snmp_usmusertable_get_instance(
    column: &mut u32,
    row_oid: &mut u32,
    row_oid_len: u8,
    cell_instance: &mut snmp_node_instance,
) -> Result<(), LwipError> {
    let engineid: String;
    let eid_len: u8;

    let engineid_oid: [u32; SNMP_V3_MAX_ENGINE_ID_LENGTH];

    let name_len: u8;
    let engineid_len: u8;

    let name_start: u8;
    let engineid_start: u8;

    snmpv3_get_engine_id(&engineid, &eid_len);

    engineid_len = row_oid[0];
    engineid_start = 1;

    if (engineid_len != eid_len) {
        /* EngineID length does not match! */
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    if (engineid_len > row_oid_len) {
        /* row OID doesn't contain enough data according to engineid_len.*/
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    /* check if incoming OID length and if values are in plausible range */
    if (!snmp_oid_in_range(
        &row_oid[engineid_start],
        engineid_len,
        usmUserTable_oid_ranges,
        engineid_len,
    )) {
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    snmp_engineid_to_oid(&engineid, &mut engineid_oid, engineid_len);

    /* Verify EngineID */
    if (snmp_oid_equal(
        &row_oid[engineid_start],
        engineid_len,
        engineid_oid,
        engineid_len,
    )) {
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    name_len = row_oid[engineid_start + engineid_len];
    name_start = engineid_start + engineid_len + 1;

    if (name_len > SNMP_V3_MAX_USER_LENGTH) {
        /* specified name is too long */
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    if (1 + engineid_len + 1 + name_len != row_oid_len) {
        /* Length of EngineID and name does not match row oid length. (+2 for length fields)*/
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    /* check if incoming OID length and if values are in plausible range */
    if (!snmp_oid_in_range(
        &row_oid[name_start],
        name_len,
        usmUserTable_oid_ranges,
        name_len,
    )) {
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    /* Verify if user exists */
    //memset(username, 0, sizeof(username));
    snmp_oid_to_name(username, &row_oid[name_start], name_len);
    if (snmpv3_get_user(username, None, None, None, None) != ERR_OK) {
        return SNMP_ERR_NOSUCHINSTANCE;
    }

    /* Save name in reference pointer to make it easier to handle later on */
    cell_instance.reference.ptr = username;
    cell_instance.reference_len = name_len;

    /* user was found */
    return SNMP_ERR_NOERROR;
}

/*
 * valid oid options
 * <oid>
 * <oid>.<EngineID length>
 * <oid>.<EngineID length>.<partial EngineID>
 * <oid>.<EngineID length>.<EngineID>
 * <oid>.<EngineID length>.<EngineID>.<UserName length>
 * <oid>.<EngineID length>.<EngineID>.<UserName length>.<partial UserName>
 * <oid>.<EngineID length>.<EngineID>.<UserName length>.<UserName>
 *
 */
pub fn snmp_usmusertable_get_next_instance(
    column: &mut u32,
    row_oid: &mut snmp_obj_id,
    cell_instance: &mut snmp_node_instance,
) -> Result<(), LwipError> {
    let engineid: String;
    let eid_len: u8;

    let engineid_oid: [u32; SNMP_V3_MAX_ENGINE_ID_LENGTH];

    let name_len: u8;
    let engineid_len: u8;

    let name_start: u8;
    let engineid_start: u8 = 1;
    let i: u8;

    let state: snmp_next_oid_state;

    let result_temp: [u32; LWIP_ARRAYSIZE(usmUserTable_oid_ranges)];

    snmpv3_get_engine_id(&engineid, &eid_len);

    /* If EngineID might be given */
    if (row_oid.len > 0) {
        engineid_len = row_oid.id[0];
        engineid_start = 1;

        if (engineid_len != eid_len) {
            /* EngineID length does not match! */
            return SNMP_ERR_NOSUCHINSTANCE;
        }

        if (engineid_len > row_oid.len) {
            /* Verify partial EngineID */
            snmp_engineid_to_oid(&engineid, &mut engineid_oid, row_oid.len - 1);
            if (!snmp_oid_equal(
                &row_oid.id[engineid_start],
                row_oid.len - 1,
                engineid_oid,
                row_oid.len - 1,
            )) {
                return SNMP_ERR_NOSUCHINSTANCE;
            }
        } else {
            /* Verify complete EngineID */
            snmp_engineid_to_oid(&engineid, &mut engineid_oid, engineid_len);
            if (!snmp_oid_equal(
                &row_oid.id[engineid_start],
                engineid_len,
                engineid_oid,
                engineid_len,
            )) {
                return SNMP_ERR_NOSUCHINSTANCE;
            }
        }

        /* At this point, the given EngineID (partially) matches the local EngineID.*/

        /* If name might also be given */
        if (row_oid.len > engineid_start + engineid_len) {
            name_len = row_oid.id[engineid_start + engineid_len];
            name_start = engineid_start + engineid_len + 1;

            if (name_len > SNMP_V3_MAX_USER_LENGTH) {
                /* specified name is too long, max length is 32 according to mib file.*/
                return SNMP_ERR_NOSUCHINSTANCE;
            }

            if (row_oid.len < engineid_len + name_len + 2) {
                /* Partial name given according to oid.*/
                let tmplen: u8 = row_oid.len - engineid_len - 2;
                if (!snmp_oid_in_range(
                    &row_oid.id[name_start],
                    tmplen,
                    usmUserTable_oid_ranges,
                    tmplen,
                )) {
                    return SNMP_ERR_NOSUCHINSTANCE;
                }
            } else {
                /* Full name given according to oid. Also test for too much data.*/
                let tmplen: u8 = row_oid.len - engineid_len - 2;
                if (!snmp_oid_in_range(
                    &row_oid.id[name_start],
                    name_len,
                    usmUserTable_oid_ranges,
                    tmplen,
                )) {
                    return SNMP_ERR_NOSUCHINSTANCE;
                }
            }

            /* At this pothe: i32 EngineID and (partial) UserName match the local EngineID and UserName.*/
        }
    }

    /* init struct to search next oid */
    snmp_next_oid_init(
        &state,
        row_oid.id,
        row_oid.len,
        result_temp,
        LWIP_ARRAYSIZE(usmUserTable_oid_ranges),
    );

    for i in 0..snmpv3_get_amount_of_users() {
        let test_oid: [u32; LWIP_ARRAYSIZE(usmUserTable_oid_ranges)];

        test_oid[0] = eid_len;
        snmp_engineid_to_oid(&engineid, &test_oid[1], eid_len);

        snmpv3_get_username(username, i);

        test_oid[1 + eid_len] = strlen(username);
        snmp_name_to_oid(username, &test_oid[2 + eid_len], strlen(username));

        /* check generated OID: is it a candidate for the next one? */
        // snmp_next_oid_check(&state, test_oid, (1 + eid_len + 1 + strlen(username)), LWIP_PTR_NUMERIC_CAST(void *, i));
    }

    /* did we find a next one? */
    if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
        snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
        /* store username for subsequent operations (get/test/set) */
        //memset(username, 0, sizeof(username));
        snmpv3_get_username(username, LWIP_PTR_NUMERIC_CAST(u8, state.reference));
        cell_instance.reference.ptr = username;
        cell_instance.reference_len = strlen(username);
        return SNMP_ERR_NOERROR;
    }

    /* not found */
    return SNMP_ERR_NOSUCHINSTANCE;
}

pub fn usmusertable_get_value(cell_instance: &mut snmp_node_instance, value: &mut Vec<u8>) -> i16 {
    let storage_type: snmpv3_user_storagetype_t;

    match (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance.instance_oid.id)) {
        3 => {
            /* usmUserSecurityName */
            MEMCPY(
                value,
                cell_instance.reference.ptr,
                cell_instance.reference_len,
            );
            return cell_instance.reference_len;
        }
        4 => {
            /* usmUserCloneFrom */
            MEMCPY(
                value,
                snmp_zero_dot_zero.id,
                snmp_zero_dot_zero.len * sizeof,
            );
            return snmp_zero_dot_zero.len * sizeof;
        }
        5 => {
            /* usmUserAuthProtocol */
            let mut auth_algo: &mut snmp_obj_id;
            let auth_algo_val: snmpv3_auth_algo_t;
            snmpv3_get_user(
                cell_instance.reference.ptr,
                &auth_algo_val,
                None,
                None,
                None,
            );
            auth_algo = snmp_auth_algo_to_oid(auth_algo_val);
            MEMCPY(value, auth_algo.id, auth_algo.len * sizeof);
            return auth_algo.len * sizeof;
        }
        6 => {
            /* usmUserAuthKeyChange */
            return 0;
        }
        7 => {
            /* usmUserOwnAuthKeyChange */
            return 0;
        }
        8 => {
            /* usmUserPrivProtocol */
            let mut priv_algo: &mut snmp_obj_id;
            let priv_algo_val: snmpv3_priv_algo_t;
            snmpv3_get_user(
                cell_instance.reference.ptr,
                None,
                None,
                &priv_algo_val,
                None,
            );
            priv_algo = snmp_priv_algo_to_oid(priv_algo_val);
            MEMCPY(value, priv_algo.id, priv_algo.len * sizeof);
            return priv_algo.len * sizeof;
        }
        9 => {
            /* usmUserPrivKeyChange */
            return 0;
        }
        10 => {
            /* usmUserOwnPrivKeyChange */
            return 0;
        }
        11 => {
            /* usmUserPublic */
            /* TODO: Implement usmUserPublic */
            return 0;
        }
        12 => {
            /* usmUserStorageType */
            snmpv3_get_user_storagetype(cell_instance.reference.ptr, &storage_type);
            *value = storage_type;
            return sizeof;
        }
        13 => {
            /* usmUserStatus */
            *value = 1; /* active */
            return sizeof;
        }
        _ => {
            //      LWIP_DEBUGF(SNMP_MIB_DEBUG, ("usmusertable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance.instance_oid.id)));
            return 0;
        }
    }
}

/* --- usmMIBObjects 1.3.6.1.6.3.15.1 ----------------------------------------------------- */
pub fn usmstats_scalars_get_value(
    node: &mut snmp_scalar_array_node_def,
    value: &mut Vec<u8>,
) -> i16 {
    let uint_ptr: &mut u32 = value;
    match (node.oid) {
        1 => {
            /* usmStatsUnsupportedSecLevels */
            *uint_ptr = snmp_stats.unsupportedseclevels;
        }
        2 => {
            /* usmStatsNotInTimeWindows */
            *uint_ptr = snmp_stats.notintimewindows;
        }
        3 => {
            /* usmStatsUnknownUserNames */
            *uint_ptr = snmp_stats.unknownusernames;
        }
        4 => {
            /* usmStatsUnknownEngineIDs */
            *uint_ptr = snmp_stats.unknownengineids;
        }
        5 => {
            /* usmStatsWrongDigests */
            *uint_ptr = snmp_stats.wrongdigests;
        }
        6 => {
            /* usmStatsDecryptionErrors */
            *uint_ptr = snmp_stats.decryptionerrors;
        }
        _ => {
            //      LWIP_DEBUGF(SNMP_MIB_DEBUG, ("usmstats_scalars_get_value(): unknown id: %"S32_F"\n", node.oid));
            return 0;
        }
    }

    return sizeof(*uint_ptr);
}

/* --- snmpUsmMIB  ----------------------------------------------------- */

/* --- usmUser 1.3.6.1.6.3.15.1.2 ----------------------------------------------------- */

pub const usmusertable_columns: [snmp_table_col_def; 11] = [
    snmp_table_col_def::new(3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserSecurityName */
    snmp_table_col_def::new(4, SNMP_ASN1_TYPE_OBJECT_ID, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserCloneFrom */
    snmp_table_col_def::new(5, SNMP_ASN1_TYPE_OBJECT_ID, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserAuthProtocol */
    snmp_table_col_def::new(6, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserAuthKeyChange */
    snmp_table_col_def::new(7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserOwnAuthKeyChange */
    snmp_table_col_def::new(8, SNMP_ASN1_TYPE_OBJECT_ID, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserPrivProtocol */
    snmp_table_col_def::new(9, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserPrivKeyChange */
    snmp_table_col_def::new(
        10,
        SNMP_ASN1_TYPE_OCTET_STRING,
        SNMP_NODE_INSTANCE_READ_ONLY,
    ), /* usmUserOwnPrivKeyChange */
    snmp_table_col_def::new(
        11,
        SNMP_ASN1_TYPE_OCTET_STRING,
        SNMP_NODE_INSTANCE_READ_ONLY,
    ), /* usmUserPublic */
    snmp_table_col_def::new(12, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserStorageType */
    snmp_table_col_def::new(13, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmUserStatus */
];
pub const usmusertable: snmp_table_node = SNMP_TABLE_CREATE(
    2,
    usmusertable_columns,
    usmusertable_get_instance,
    usmusertable_get_next_instance,
    usmusertable_get_value,
    None,
    None,
);

// static const const: &mut snmp_node usmuser_subnodes[] = {
//   &usmusertable.node.node
// };
pub const usmuser_treenode: snmp_tree_node = SNMP_CREATE_TREE_NODE(2, usmuser_subnodes);

/* --- usmMIBObjects 1.3.6.1.6.3.15.1 ----------------------------------------------------- */
pub const usmstats_scalars_nodes: [snmp_scalar_array_node_def] = [
    snmp_scalar_array_node_def::new(1, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsUnsupportedSecLevels */
    snmp_scalar_array_node_def::new(2, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsNotInTimeWindows */
    snmp_scalar_array_node_def::new(3, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsUnknownUserNames */
    snmp_scalar_array_node_def::new(4, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsUnknownEngineIDs */
    snmp_scalar_array_node_def::new(5, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsWrongDigests */
    snmp_scalar_array_node_def::new(6, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY), /* usmStatsDecryptionErrors */
];
pub const usmstats_scalars: snmp_scalar_array_node = SNMP_SCALAR_CREATE_ARRAY_NODE(
    1,
    usmstats_scalars_nodes,
    usmstats_scalars_get_value,
    None,
    None,
);

// static const const: &mut snmp_node usmmibobjects_subnodes[] = {
//   &usmstats_scalars.node.node,
//   &usmuser_treenode.node
// };
pub const usmmibobjects_treenode: snmp_tree_node = SNMP_CREATE_TREE_NODE(1, usmmibobjects_subnodes);

/* --- snmpUsmMIB  ----------------------------------------------------- */
// static const const: &mut snmp_node snmpusmmib_subnodes[] = {
//   &usmmibobjects_treenode.node
// };
pub const snmpusmmib_root: snmp_tree_node = SNMP_CREATE_TREE_NODE(15, snmpusmmib_subnodes);
pub const snmpusmmib_base_oid: [u32; 7] = [1, 3, 6, 1, 6, 3, 15];
pub const snmpusmmib: snmp_mib = snmp_mib::new(
    snmpusmmib_base_oid,
    LWIP_ARRAYSIZE(snmpusmmib_base_oid),
    &snmpusmmib_root.node,
);
