use crate::altcp::context::AlTcpContext;
use crate::core::error::LwipError;
use crate::core::defines::LwipAddr;
use crate::packetbuffer::pbuf_h::PacketBuffer;
use crate::tcp::tcpbase_h::TcpState;

// typedef err_t (*AltcpAcceptFn)(arg: &mut Vec<u8>, new_conn: &mut AltcpPcb, err: err_t);
type AltcpAcceptFn = fn(arg: &mut AlTcpPcb, new_conn: &mut AlTcpPc) -> Result<(), LwipError>;
// typedef err_t (*AltcpConnectedFn)(arg: &mut Vec<u8>, conn: &mut AltcpPcb, err: err_t);
type AltcpConnectedFunc = fn(arg: &mut AlTcpContext, conn: &mut AlTcpContext) -> Result<(), LwipError>;
// typedef err_t (*AltcpRecvFn)(arg: &mut Vec<u8>, conn: &mut AltcpPcb, p: &mut PacketBuffer, err: err_t);
type AltcpRecvFn = fn(arg: &mut Vec<u8>, conn: &mut AlTcpPcb, p: &mut PacketBuffer, err: err_t) -> err_t;
// typedef err_t (*AltcpSentFn)(arg: &mut Vec<u8>, conn: &mut AltcpPcb, len: u16);
type AltcpSentFn = fn(arg: &mut Vec<u8>, conn: &mut AlTcpPcb, len: usize) -> err_t;
// typedef err_t (*AltcpPollFn)(arg: &mut Vec<u8>, conn: &mut AltcpPcb);
type AlTcpPollFn = fn(arg: &mut Vec<u8>, conn: &mut AlTcpPcb) -> err_t;
// typedef void  (*AltcpErrFn)(arg: &mut Vec<u8>, err: err_t);
type AltcpErrFn = fn(arg: &mut AlTcpPcb, err: err_t);
// typedef struct AltcpPcb* (*AltcpNewFn)(arg: &mut Vec<u8>, ip_type: u8);
pub type AltcpNewFn = fn(arg: &mut AlTcpPcb, ip_type: u8) -> &mut AlTcpPcb;
// typedef void (*AltcpSetPollFn)(conn: &mut AltcpPcb, interval: u8);
type AltcpSetPollFn = fn(conn: &mut AlTcpPcb, u8: i32erval);
// typedef void (*AltcpRecvedFn)(conn: &mut AltcpPcb, len: u16);
type AltcpRecvedFn = fn(conn: &mut AlTcpPcb, len: usize);
// typedef err_t (*AltcpBindFn)(conn: &mut AltcpPcb,  ipaddr: &mut LwipAddr, port: u16);
type AltcpBindFn = fn(conn: &mut AlTcpPcb, ip_addr: &LwipAddr, port: u16) -> err_t;
// typedef err_t (*AltcpConnectFn)(conn: &mut AltcpPcb,  ipaddr: &mut LwipAddr, port: u16, AltcpConnectedFn connected);
type AltcpConnectFn = fn(conn: &mut AlTcpPcb, ipaddr: &LwipAddr, port: u16, connected: AltcpConnectedFn) -> err_t;
// typedef struct AltcpPcb *(*AltcpListenFn)(conn: &mut AltcpPcb, backlog: u8, err: &mut err_t);
type AltcpListenFn = fn(conn: &mut AlTcpPcb, backlog: u8, err: &mut err_t) -> &mut AlTcpPcb;
// typedef void  (*AltcpAbortFn)(conn: &mut AltcpPcb);
type AltcpAbortFn = fn(conn: &mut AlTcpPcb);
// typedef err_t (*AltcpCloseFn)(conn: &mut AltcpPcb);
type AltcpCloseFn = fn(conn: &mut AlTcpPcb) -> err_t;
// typedef err_t (*AltcpShutdownFn)(conn: &mut AltcpPcb, shut_rx: i32, shut_tx: i32);
type AltcpShutdownFn = fn(conn: &mut AlTcpPcb, shut_rx: i32, shut_tx: i32) -> err_t;
// typedef err_t (*AltcpWriteFn)(conn: &mut AltcpPcb, dataptr: &Vec<u8>, len: u16, apiflags: u8);
 type AltcpWriteFn = fn(conn: &mut AlTcpPcb, dataptr: &[u8], len: usize, apiflags: u8) -> err_t;
// typedef err_t (*AltcpOutputFn)(conn: &mut AltcpPcb);
type AltcpOutputFn = fn(conn: &mut AlTcpPcb) -> err_t;
// typedef u16 (*AltcpMssFn)(conn: &mut AltcpPcb);
type AltcpMssFn = fn(conn: &mut AlTcpPcb) -> u16;
// typedef u16 (*AltcpSndbufFn)(conn: &mut AltcpPcb);
type AltcpSndbufFn = fn(conn: &mut AlTcpPcb) -> u16;
// typedef u16 (*AltcpSndqueuelenFn)(conn: &mut AltcpPcb);
type AltcpSndqueuelenFn = fn(conn: &mut AlTcpPcb) -> u16;
// typedef void  (*AltcpNagleDisableFn)(conn: &mut AltcpPcb);
type AltcpNagleDisableFn = fn(conn: &mut AlTcpPcb);
// typedef void  (*AltcpNagleEnableFn)(conn: &mut AltcpPcb);
type AltcpNagleEnableFn = fn(conn: &mut AlTcpPcb);
// typedef int   (*AltcpNagleDisabledFn)(conn: &mut AltcpPcb);
type AltcpNagleDisabledFn = fn(conn: &mut AlTcpPcb) -> i32;
// typedef void  (*AltcpSetprioFn)(conn: &mut AltcpPcb, prio: u8);
type AltcpSetprioFn = fn(conn: &mut AlTcpPcb, prio: u8);
// typedef void  (*AltcpDeallocFn)(conn: &mut AltcpPcb);
type AltcpDeallocFn = fn(conn: &mut AlTcpPcb);
// typedef err_t (*AltcpGetTcpAddrinfoFn)(conn: &mut AltcpPcb, local: i32, addr: &mut LwipAddr, port: &mut u16);
type AltcpGetTcpAddrinfoFn = fn(conn: &mut AlTcpPcb, local: i32, addr: &LwipAddr, port: &u16) -> err_t;
// typedef LwipAddr *(*AltcpGetIpFn)(conn: &mut AltcpPcb, local: i32);
type AltcpGetIpFn = fn(conn: &mut AlTcpPcb, local: i32) -> LwipAddr;
// typedef u16 (*AltcpGetPortFn)(conn: &mut AltcpPcb, local: i32);
type AltcpGetPortFn = fn(conn: &mut AlTcpPcb, local: i32) -> u16;
// typedef enum tcp_state (*AltcpDbgGetTcpStateFn)(conn: &mut AltcpPcb);
type AltcpDbgGetTcpStateFn = fn(conn: &mut AlTcpPcb) -> TcpState;
