//! Standard error codes
pub const ENOENT: u32 = 2; //  No such file or directory 
pub const ESRCH: u32 = 3; //  No such process 
pub const EINTR: u32 = 4; //  Interrupted system call 
pub const EIO: u32 = 5; //  I/O error 
pub const ENXIO: u32 = 6; //  No such device or address 
pub const E2BIG: u32 = 7; //  Arg list too long 
pub const ENOEXEC: u32 = 8; //  Exec format error 
pub const EBADF: u32 = 9; //  Bad file number 
pub const ECHILD: u32 = 10; //  No child processes 
pub const EAGAIN: u32 = 11; //  Try again 
pub const ENOMEM: u32 = 12; //  Out of memory 
pub const EACCES: u32 = 13; //  Permission denied 
pub const EFAULT: u32 = 14; //  Bad address 
pub const ENOTBLK: u32 = 15; //  Block device required 
pub const EBUSY: u32 = 16; //  Device or resource busy 
pub const EEXIST: u32 = 17; //  File exists 
pub const EXDEV: u32 = 18; //  Cross-device link 
pub const ENODEV: u32 = 19; //  No such device 
pub const ENOTDIR: u32 = 20; //  Not a directory 
pub const EISDIR: u32 = 21; //  Is a directory 
pub const EINVAL: u32 = 22; //  Invalid argument 
pub const ENFILE: u32 = 23; //  File table overflow 
pub const EMFILE: u32 = 24; //  Too many open files 
pub const ENOTTY: u32 = 25; //  Not a typewriter 
pub const ETXTBSY: u32 = 26; //  Text file busy 
pub const EFBIG: u32 = 27; //  File too large 
pub const ENOSPC: u32 = 28; //  No space left on device 
pub const ESPIPE: u32 = 29; //  Illegal seek 
pub const EROFS: u32 = 30; //  Read-only file system 
pub const EMLINK: u32 = 31; //  Too many links 
pub const EPIPE: u32 = 32; //  Broken pipe 
pub const EDOM: u32 = 33; //  Math argument out of domain of func 
pub const ERANGE: u32 = 34; //  Math result not representable 
pub const EDEADLK: u32 = 35; //  Resource deadlock would occur 
pub const ENAMETOOLONG: u32 = 36; //  File name too long 
pub const ENOLCK: u32 = 37; //  No record locks available 
pub const ENOSYS: u32 = 38; //  Function not implemented 
pub const ENOTEMPTY: u32 = 39; //  Directory not empty 
pub const ELOOP: u32 = 40; //  Too many symbolic links encountered 
pub const EWOULDBLOCK: u32 = EAGAIN; //  Operation would block 
pub const ENOMSG: u32 = 42; //  No message of desired type 
pub const EIDRM: u32 = 43; //  Identifier removed 
pub const ECHRNG: u32 = 44; //  Channel number out of range 
pub const EL2NSYNC: u32 = 45; //  Level 2 not synchronized 
pub const EL3HLT: u32 = 46; //  Level 3 halted 
pub const EL3RST: u32 = 47; //  Level 3 reset 
pub const ELNRNG: u32 = 48; //  Link number out of range 
pub const EUNATCH: u32 = 49; //  Protocol driver not attached 
pub const ENOCSI: u32 = 50; //  No CSI structure available 
pub const EL2HLT: u32 = 51; //  Level 2 halted 
pub const EBADE: u32 = 52; //  Invalid exchange 
pub const EBADR: u32 = 53; //  Invalid request descriptor 
pub const EXFULL: u32 = 54; //  Exchange full 
pub const ENOANO: u32 = 55; //  No anode 
pub const EBADRQC: u32 = 56; //  Invalid request code 
pub const EBADSLT: u32 = 57; //  Invalid slot 

pub const EDEADLOCK: u32 = EDEADLK;

pub const EBFONT: u32 = 59; //  Bad font file format 
pub const ENOSTR: u32 = 60; //  Device not a stream 
pub const ENODATA: u32 = 61; //  No data available 
pub const ETIME: u32 = 62; //  Timer expired 
pub const ENOSR: u32 = 63; //  Out of streams resources 
pub const ENONET: u32 = 64; //  Machine is not on the network 
pub const ENOPKG: u32 = 65; //  Package not installed 
pub const EREMOTE: u32 = 66; //  Object is remote 
pub const ENOLINK: u32 = 67; //  Link has been severed 
pub const EADV: u32 = 68; //  Advertise error 
pub const ESRMNT: u32 = 69; //  Srmount error 
pub const ECOMM: u32 = 70; //  Communication error on send 
pub const EPROTO: u32 = 71; //  Protocol error 
pub const EMULTIHOP: u32 = 72; //  Multihop attempted 
pub const EDOTDOT: u32 = 73; //  RFS specific error 
pub const EBADMSG: u32 = 74; //  Not a data message 
pub const EOVERFLOW: u32 = 75; //  Value too large for defined data type 
pub const ENOTUNIQ: u32 = 76; //  Name not unique on network 
pub const EBADFD: u32 = 77; //  File descriptor in bad state 
pub const EREMCHG: u32 = 78; //  Remote address changed 
pub const ELIBACC: u32 = 79; //  Can not access a needed shared library 
pub const ELIBBAD: u32 = 80; //  Accessing a corrupted shared library 
pub const ELIBSCN: u32 = 81; //  .lib section in a.out corrupted 
pub const ELIBMAX: u32 = 82; //  Attempting to link in too many shared libraries 
pub const ELIBEXEC: u32 = 83; //  Cannot exec a shared library directly 
pub const EILSEQ: u32 = 84; //  Illegal byte sequence 
pub const ERESTART: u32 = 85; //  Interrupted system call should be restarted 
pub const ESTRPIPE: u32 = 86; //  Streams pipe error 
pub const EUSERS: u32 = 87; //  Too many users 
pub const ENOTSOCK: u32 = 88; //  Socket operation on non-socket 
pub const EDESTADDRREQ: u32 = 89; //  Destination address required 
pub const EMSGSIZE: u32 = 90; //  Message too long 
pub const EPROTOTYPE: u32 = 91; //  Protocol wrong type for socket 
pub const ENOPROTOOPT: u32 = 92; //  Protocol not available 
pub const EPROTONOSUPPORT: u32 = 93; //  Protocol not supported 
pub const ESOCKTNOSUPPORT: u32 = 94; //  Socket type not supported 
pub const EOPNOTSUPP: u32 = 95; //  Operation not supported on transport endpoint 
pub const EPFNOSUPPORT: u32 = 96; //  Protocol family not supported 
pub const EAFNOSUPPORT: u32 = 97; //  Address family not supported by protocol 
pub const EADDRINUSE: u32 = 98; //  Address already in use 
pub const EADDRNOTAVAIL: u32 = 99; //  Cannot assign requested address 
pub const ENETDOWN: u32 = 100; //  Network is down 
pub const ENETUNREACH: u32 = 101; //  Network is unreachable 
pub const ENETRESET: u32 = 102; //  Network dropped connection because of reset 
pub const ECONNABORTED: u32 = 103; //  Software caused connection abort 
pub const ECONNRESET: u32 = 104; //  Connection reset by peer 
pub const ENOBUFS: u32 = 105; //  No buffer space available 
pub const EISCONN: u32 = 106; //  Transport endpois: i32 already connected 
pub const ENOTCONN: u32 = 107; //  Transport endpois: i32 not connected 
pub const ESHUTDOWN: u32 = 108; //  Cannot send after transport endposhutdown: i32 
pub const ETOOMANYREFS: u32 = 109; //  Too many references: cannot splice 
pub const ETIMEDOUT: u32 = 110; //  Connection timed out 
pub const ECONNREFUSED: u32 = 111; //  Connection refused 
pub const EHOSTDOWN: u32 = 112; //  Host is down 
pub const EHOSTUNREACH: u32 = 113; //  No route to host 
pub const EALREADY: u32 = 114; //  Operation already in progress 
pub const EINPROGRESS: u32 = 115; //  Operation now in progress 
pub const ESTALE: u32 = 116; //  Stale NFS file handle 
pub const EUCLEAN: u32 = 117; //  Structure needs cleaning 
pub const ENOTNAM: u32 = 118; //  Not a XENIX named type file 
pub const ENAVAIL: u32 = 119; //  No XENIX semaphores available 
pub const EISNAM: u32 = 120; //  Is a named type file 
pub const EREMOTEIO: u32 = 121; //  Remote I/O error 
pub const EDQUOT: u32 = 122; //  Quota exceeded 

pub const ENOMEDIUM: u32 = 123; //  No medium found 
pub const EMEDIUMTYPE: u32 = 124; //  Wrong medium type 
