/*
Generated by LwipMibCompiler
*/


#define LWIP_HDR_APPS_SNMP_FRAMEWORK_MIB_H





extern "C" {




extern const struct snmp_obj_id usmNoAuthProtocol;
extern const struct snmp_obj_id usmHMACMD5AuthProtocol;
extern const struct snmp_obj_id usmHMACSHAAuthProtocol;

extern const struct snmp_obj_id usmNoPrivProtocol;
extern const struct snmp_obj_id usmDESPrivProtocol;
extern const struct snmp_obj_id usmAESPrivProtocol;

extern const struct snmp_mib snmpframeworkmib;


}




