/*
Generated by LwipMibCompiler
*/




// #include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP


 /* __cplusplus */

// #include "lwip/apps/snmp_core.h"

extern const struct snmp_mib snmpusmmib;


 /* __cplusplus */

 /* LWIP_SNMP */
 /* LWIP_HDR_APPS_SNMP_USER_BASED_SM_MIB_H */
